"""
execution/fetch_qa_transcript.py
--------------------------------
Fetch ONLY the Q&A segment of an earnings call from free, no-auth aggregator
sites (roic.ai → stockanalysis.com → tickertrends.io). First hit wins.

Why Q&A only:
  - Prepared remarks are reproducible from the press release + investor deck,
    which `execution/process_ir_documents.py` already summarizes via
    `generate_press_release_summary` / `generate_presentation_brief`.
  - The Q&A segment is the unique audio-only content — analysts probing the
    edges of management's prepared message — and is exactly what say-do
    consistency analysis needs.
  - Aggregators publish Q&A pre-segmented and speaker-tagged, which is
    structurally cleaner than diarizing audio.

Output:
  transcripts/raw/<TICKER>_Q<N>_<YEAR>.txt — synthesizer-banner header + raw
  Q&A text. Registered with source=aggregator_<name>; QA validator routes to
  the synthesized-flavor checks.

Use as the PRIMARY pull path; `fetch_audio_transcripts.py` becomes the audio
fallback for quarters not yet indexed by any aggregator.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from pydantic import BaseModel, Field, ValidationError, field_validator

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
sys.path.append(str(SRC_DIR))

import db  # noqa: E402
import index_manager  # noqa: E402
from aggregator_sources import (  # noqa: E402
    SOURCES,
    AggregatorHit,
    fetch_qa_with_fallback,
)
from alias_manager import resolve_ticker  # noqa: E402
from pipeline.source_policy import (  # noqa: E402
    ArtifactKind,
    CollectionSource,
    StoredCollectionAuthorization,
    authorize_stored_collection_target,
    reported_quarter_is_in_window,
)
from transcript_qa import (  # noqa: E402
    QaStatus,
    validate_synthesized_transcript,
)

RAW_DIR = PROJECT_ROOT / "transcripts" / "raw"


def _policy_today() -> date:
    return date.today()


class FetchQaSpec(BaseModel):
    ticker: str
    year: int = Field(ge=2000, le=2100)
    quarter: int = Field(ge=1, le=4)

    @field_validator("ticker")
    @classmethod
    def _upper(cls, v: str) -> str:
        return v.strip().upper()


@dataclass(frozen=True)
class FetchQaResult:
    ticker: str
    year: int
    quarter: int
    output_path: Path
    source_name: str
    page_url: str


class TranscriptCollectionPolicyError(RuntimeError):
    """The stored role or reported-quarter window denied a network fetch."""


def _authorize_fetch(
    spec: FetchQaSpec,
    *,
    db_path: Path,
    owner_requested: bool,
    as_of: date,
) -> StoredCollectionAuthorization | None:
    canonical = resolve_ticker(spec.ticker)
    authorization = authorize_stored_collection_target(
        db_path,
        canonical,
        requested=owner_requested,
        source=CollectionSource.TRANSCRIPT,
        artifact_kind=ArtifactKind.TEXT_TRANSCRIPT,
    )
    in_window = authorization.fiscal_year_end_month is not None and reported_quarter_is_in_window(
        fiscal_year=spec.year,
        fiscal_quarter=spec.quarter,
        fiscal_year_end_month=authorization.fiscal_year_end_month,
        as_of=as_of,
    )
    if authorization.allowed and in_window:
        return authorization
    reason = (
        "reported_quarter_window_denied"
        if authorization.allowed
        else (
            authorization.decision.reason.value
            if authorization.decision is not None
            else authorization.status.value
        )
    )
    sys.stderr.write(
        json.dumps(
            {
                "event": "source_collection_policy_denied",
                "ticker": canonical,
                "source": CollectionSource.TRANSCRIPT.value,
                "artifact_kind": ArtifactKind.TEXT_TRANSCRIPT.value,
                "reason": reason,
            },
            sort_keys=True,
        )
        + "\n"
    )
    return None


def _build_header(spec: FetchQaSpec, hit: AggregatorHit) -> str:
    """Build the file's banner header.

    Deliberately excludes a wall-clock fetch timestamp: this header is
    hashed (`sha256_of`) to decide whether a re-fetch is byte-identical to
    what's already ingested. A `Built at: {datetime.now()}` line used to
    live here and made every re-fetch hash differently even when the
    underlying Q&A text hadn't changed, defeating that idempotency check
    (root cause of the 2026-07-25 transcript-duplication incident — see
    `execution/dedupe_transcripts.py`). Fetch time is already tracked in
    `.tmp/transcript_index.json`'s `indexed_at`; it doesn't need to also be
    inside the hashed file content.
    """
    canonical = resolve_ticker(spec.ticker)
    return (
        f"=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===\n"
        f"Generated by execution/fetch_qa_transcript.py from a free aggregator.\n"
        f"This file contains the QUESTION-AND-ANSWER segment only — prepared\n"
        f"remarks are reproducible from the press release + investor deck and\n"
        f"are excluded here to keep the input focused for say-do analysis.\n"
        f"\n"
        f"Ticker:    {canonical}\n"
        f"Period:    Q{spec.quarter} {spec.year}\n"
        f"Source:    aggregator_{hit.source_name} ({hit.page_url})\n"
        f"\n"
        f"=== Q&A SEGMENT ===\n"
    )


def fetch_qa(
    spec: FetchQaSpec,
    force: bool = False,
    *,
    db_path: Path,
    owner_requested: bool,
    as_of: date | None = None,
) -> FetchQaResult | None:
    canonical = resolve_ticker(spec.ticker)
    authorization = _authorize_fetch(
        spec,
        db_path=db_path,
        owner_requested=owner_requested,
        as_of=_policy_today() if as_of is None else as_of,
    )
    if authorization is None:
        return None
    qlabel = f"Q{spec.quarter}"
    output_path = RAW_DIR / f"{canonical}_{qlabel}_{spec.year}.txt"

    if output_path.exists() and not force:
        print(
            f"[skip] {canonical} {qlabel} {spec.year}: transcript file already exists. "
            f"Pass --force to overwrite."
        )
        return None

    hit, tried = fetch_qa_with_fallback(canonical, spec.year, spec.quarter)
    if hit is None:
        print(
            f"[miss] {canonical} {qlabel} {spec.year}: no aggregator hit. "
            f"Tried: {', '.join(tried)}. "
            "No policy-approved audio/webcast fallback is available."
        )
        return None

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_build_header(spec, hit) + hit.qa_text, encoding="utf-8")

    qa_result = validate_synthesized_transcript(output_path)
    source_label = f"aggregator_{hit.source_name}"
    index_manager.register_transcript(
        canonical,
        spec.year,
        qlabel,
        source=source_label,
        filepath=output_path.name,
        has_qa=True,  # this IS the Q&A
        qa_status=qa_result.status.value,
        qa_details=qa_result.model_dump(mode="json"),
    )
    if qa_result.status == QaStatus.OK:
        print(
            f"[done] {output_path.name}  source={source_label}  qa_chars={len(hit.qa_text)}  qa=ok"
        )
    else:
        print(
            f"[done-qa-failed] {output_path.name}  source={source_label}  "
            f"issues={len(qa_result.issues)}"
        )
        for issue in qa_result.issues:
            print(f"      - {issue}")

    return FetchQaResult(
        ticker=canonical,
        year=spec.year,
        quarter=spec.quarter,
        output_path=output_path,
        source_name=hit.source_name,
        page_url=hit.page_url,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fetch the Q&A segment of an earnings call from free aggregators."
    )
    parser.add_argument("--ticker", required=True, help="Stock ticker (e.g. NOW)")
    parser.add_argument("--year", required=True, type=int)
    parser.add_argument("--quarter", required=True, type=int, choices=[1, 2, 3, 4])
    parser.add_argument(
        "--db",
        type=Path,
        default=Path(db.DB_PATH),
        help="portfolio.db containing the active stored company role",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing transcript file.",
    )
    parser.add_argument(
        "--list-sources",
        action="store_true",
        help="Print the configured aggregator chain and exit.",
    )
    args = parser.parse_args()

    if args.list_sources:
        print("Aggregator fallback chain (priority order):")
        for s in SOURCES:
            print(f"  - {s.name}")
        return

    try:
        spec = FetchQaSpec(ticker=args.ticker, year=args.year, quarter=args.quarter)
    except ValidationError as e:
        parser.error(str(e))

    fetch_qa(spec, force=args.force, db_path=args.db, owner_requested=True)


if __name__ == "__main__":
    main()
