"""
execution/synthesize_quarterly_update.py
----------------------------------------
Layer 3 fallback for quarters where no earnings call audio is available on
YouTube (e.g. NVO Q4 2025, RBRK Q4 FY25). Builds a *synthesized transcript*
from text sources so downstream consumers — say-do pairwise analysis, thesis
tracker, master-PDF builder — can ingest the quarter the same way they would
a real Whisper transcript.

Sources, in order of priority:
  1. Company press release / quarterly update (URL or local PDF)
  2. FMP financial snapshot for the period (income / balance / cashflow / key metrics)
  3. Optional external recap URLs (Motley Fool, Yahoo Finance, etc.)

Output:
  transcripts/raw/{TICKER}_Q{N}_{YEAR}.txt

The output begins with a clearly labeled banner so downstream consumers — and
anyone re-reading the file — can tell at a glance that this is a synthesized
quarterly update, not a verbatim earnings call. Provenance for every section
is recorded in the file header.

Usage examples:
    python execution/synthesize_quarterly_update.py \\
        --ticker NVO --year 2025 --quarter 4 \\
        --press-release-url https://www.novonordisk.com/.../q4-2025.html \\
        --recap-url https://seekingalpha.com/article/4865705 \\
        --recap-url https://www.fool.com/...

    python execution/synthesize_quarterly_update.py \\
        --ticker RBRK --year 2025 --quarter 4 \\
        --press-release-pdf data/raw/ir/RBRK/Q4FY25_press_release.pdf
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from pydantic import BaseModel, Field, HttpUrl, field_validator
from pypdf import PdfReader

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
SRC_DIR = PROJECT_ROOT / "src"
sys.path.append(str(SRC_DIR))

from alias_manager import resolve_ticker  # noqa: E402
import index_manager  # noqa: E402
from transcript_qa import QaStatus, validate_synthesized_transcript  # noqa: E402

RAW_DIR = PROJECT_ROOT / "transcripts" / "raw"
TMP_DIR = PROJECT_ROOT / ".tmp"
ENV_PATH = PROJECT_ROOT / ".env"
IR_DOCS_ROOT = PROJECT_ROOT / "micro_thesis" / "sources"

load_dotenv(ENV_PATH)
FMP_API_KEY = os.environ.get("FMP_API_KEY", "")
# FMP retired the /api/v3/<endpoint>/<ticker> pattern in late 2025. Current
# tier uses /stable/<endpoint>?symbol=<TICKER>&period=quarter&apikey=...
FMP_BASE = "https://financialmodelingprep.com/stable"

REQUESTS_TIMEOUT = (10, 30)
# Use a real-browser UA — many IR / aggregator sites block obvious bot strings.
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)

SYNTH_BANNER = (
    "=== SYNTHESIZED QUARTERLY UPDATE — NOT A VERBATIM CALL TRANSCRIPT ===\n"
    "Generated by execution/synthesize_quarterly_update.py because no\n"
    "live earnings call audio was available on YouTube for this quarter.\n"
    "Use for thesis tracking, say-do continuity, and high-level summary;\n"
    "DO NOT cite as direct management quotes from a live call.\n"
)


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class FmpPeriod(str, Enum):
    QUARTER = "quarter"
    ANNUAL = "annual"


class SynthInput(BaseModel):
    ticker: str
    year: int = Field(ge=2000, le=2100)
    quarter: int = Field(ge=1, le=4)
    press_release_url: HttpUrl | None = None
    press_release_pdf: Path | None = None
    press_release_text: str | None = None  # last-resort manual paste
    recap_urls: list[HttpUrl] = Field(default_factory=list)
    ir_pdfs: list[Path] = Field(default_factory=list)  # explicit IR docs
    auto_ir_scan: bool = True                          # also scan IR_DOCS_ROOT
    fmp_period_end_hint: str | None = None             # e.g. "2025-12-31" if known

    @field_validator("ticker")
    @classmethod
    def _upper(cls, v: str) -> str:
        return v.strip().upper()

    @field_validator("press_release_pdf")
    @classmethod
    def _pdf_exists(cls, v: Path | None) -> Path | None:
        if v is not None and not v.exists():
            raise ValueError(f"press-release PDF not found: {v}")
        return v

    @field_validator("ir_pdfs")
    @classmethod
    def _all_ir_exist(cls, v: list[Path]) -> list[Path]:
        for p in v:
            if not p.exists():
                raise ValueError(f"--ir-pdf path not found: {p}")
        return v


@dataclass(frozen=True)
class Section:
    title: str
    body: str
    source_label: str


@dataclass(frozen=True)
class SynthResult:
    ticker: str
    year: int
    quarter: int
    output_path: Path
    sections_written: int


# ---------------------------------------------------------------------------
# Source extractors
# ---------------------------------------------------------------------------


def _http_get(url: str) -> str:
    resp = requests.get(
        url,
        timeout=REQUESTS_TIMEOUT,
        headers={"User-Agent": USER_AGENT},
    )
    resp.raise_for_status()
    return resp.text


def _extract_main_text_from_html(html: str) -> str:
    soup = BeautifulSoup(html, "lxml")
    for tag in soup(["script", "style", "noscript", "nav", "footer", "header", "form", "aside"]):
        tag.decompose()
    main = soup.find("main") or soup.find("article") or soup.body or soup
    text = main.get_text(separator="\n", strip=True)
    # Collapse runs of blank lines.
    lines = [ln.strip() for ln in text.splitlines()]
    cleaned: list[str] = []
    blank = False
    for ln in lines:
        if not ln:
            if not blank:
                cleaned.append("")
            blank = True
        else:
            cleaned.append(ln)
            blank = False
    return "\n".join(cleaned).strip()


def _extract_text_from_pdf(path: Path) -> str:
    reader = PdfReader(str(path))
    parts = [page.extract_text() or "" for page in reader.pages]
    return "\n\n".join(p.strip() for p in parts if p.strip())


def discover_ir_pdfs(ticker: str, year: int, quarter: int) -> list[Path]:
    """Scan micro_thesis/sources/<TICKER>/ for filenames containing both
    `Q<N>` and `<YEAR>` (case-insensitive). Stable sort for determinism."""
    canonical = resolve_ticker(ticker)
    folder = IR_DOCS_ROOT / canonical
    if not folder.is_dir():
        return []
    qtok = f"q{quarter}"
    ytok = str(year)
    matches: list[Path] = []
    for p in folder.iterdir():
        if not p.is_file() or p.suffix.lower() != ".pdf":
            continue
        name = p.name.lower()
        if qtok in name and ytok in name:
            matches.append(p)
    matches.sort(key=lambda p: p.name)
    return matches


def ir_doc_sections(spec: SynthInput) -> list[Section]:
    """Return one Section per IR PDF (explicit + auto-discovered, deduped)."""
    paths: list[Path] = list(spec.ir_pdfs)
    if spec.auto_ir_scan:
        for p in discover_ir_pdfs(spec.ticker, spec.year, spec.quarter):
            if p not in paths:
                paths.append(p)
    sections: list[Section] = []
    for p in paths:
        text = _extract_text_from_pdf(p)
        if not text:
            print(f"[warn] IR PDF yielded no text: {p}", file=sys.stderr)
            continue
        sections.append(
            Section(
                title=f"IR DOCUMENT — {p.name}",
                body=text,
                source_label=str(p.relative_to(PROJECT_ROOT)) if p.is_relative_to(PROJECT_ROOT) else str(p),
            )
        )
    return sections


def fetch_press_release(spec: SynthInput) -> Section | None:
    if spec.press_release_text:
        return Section(
            title="COMPANY PRESS RELEASE / QUARTERLY UPDATE",
            body=spec.press_release_text.strip(),
            source_label="manual paste (--press-release-text)",
        )
    if spec.press_release_pdf is not None:
        text = _extract_text_from_pdf(spec.press_release_pdf)
        if not text:
            raise RuntimeError(f"PDF yielded no extractable text: {spec.press_release_pdf}")
        return Section(
            title="COMPANY PRESS RELEASE / QUARTERLY UPDATE",
            body=text,
            source_label=str(spec.press_release_pdf),
        )
    if spec.press_release_url is not None:
        url = str(spec.press_release_url)
        text = _extract_main_text_from_html(_http_get(url))
        if not text:
            raise RuntimeError(f"Press release URL yielded no extractable text: {url}")
        return Section(
            title="COMPANY PRESS RELEASE / QUARTERLY UPDATE",
            body=text,
            source_label=url,
        )
    return None


# ---------------------------------------------------------------------------
# FMP snapshot
# ---------------------------------------------------------------------------


FMP_ENDPOINTS = (
    ("income-statement", "Income Statement"),
    ("balance-sheet-statement", "Balance Sheet"),
    ("cash-flow-statement", "Cash Flow"),
    ("key-metrics", "Key Metrics"),
    ("ratios", "Ratios"),
)


def _fmp_get(endpoint: str, ticker: str, period: FmpPeriod, limit: int = 16) -> list[dict[str, Any]]:
    if not FMP_API_KEY:
        raise RuntimeError("FMP_API_KEY missing from environment")
    url = f"{FMP_BASE}/{endpoint}"
    resp = requests.get(
        url,
        params={
            "symbol": ticker,
            "period": period.value,
            "limit": limit,
            "apikey": FMP_API_KEY,
        },
        timeout=REQUESTS_TIMEOUT,
    )
    if resp.status_code in (401, 403):
        raise RuntimeError(f"FMP auth error {resp.status_code} for {endpoint}: {resp.text[:200]}")
    resp.raise_for_status()
    payload = resp.json()
    if not isinstance(payload, list):
        raise RuntimeError(f"FMP {endpoint} returned non-list payload")
    return payload


def _pick_period_record(
    records: list[dict[str, Any]],
    year: int,
    quarter: int,
    period_end_hint: str | None,
) -> dict[str, Any] | None:
    if not records:
        return None
    if period_end_hint:
        for r in records:
            if r.get("date") == period_end_hint:
                return r
    target = f"Q{quarter}"
    for r in records:
        if str(r.get("calendarYear")) == str(year) and r.get("period") == target:
            return r
    return None


def fetch_fmp_snapshot(spec: SynthInput) -> Section | None:
    canonical = resolve_ticker(spec.ticker)
    if not FMP_API_KEY:
        print("[warn] FMP_API_KEY not set — skipping FMP snapshot", file=sys.stderr)
        return None

    blocks: list[str] = []
    matched_period_end: str | None = None
    for endpoint, label in FMP_ENDPOINTS:
        records = _fmp_get(endpoint, canonical, FmpPeriod.QUARTER, limit=16)
        record = _pick_period_record(records, spec.year, spec.quarter, spec.fmp_period_end_hint)
        if record is None:
            blocks.append(f"-- {label}: no record matched ({canonical} Q{spec.quarter} {spec.year})\n")
            continue
        matched_period_end = record.get("date") or matched_period_end
        blocks.append(
            f"-- {label} (period_end={record.get('date')}, currency={record.get('reportedCurrency')}) --\n"
            + json.dumps(record, indent=2, default=str)
            + "\n"
        )

    body = "\n".join(blocks).strip()
    if not body:
        return None
    return Section(
        title=f"FMP FINANCIAL SNAPSHOT (period_end={matched_period_end or 'unknown'})",
        body=body,
        source_label=f"FMP /stable/ quarterly statements for {canonical}",
    )


# ---------------------------------------------------------------------------
# External recaps
# ---------------------------------------------------------------------------


def fetch_recaps(spec: SynthInput) -> list[Section]:
    sections: list[Section] = []
    for url in spec.recap_urls:
        url_str = str(url)
        text = _extract_main_text_from_html(_http_get(url_str))
        if not text:
            print(f"[warn] recap URL produced no text: {url_str}", file=sys.stderr)
            continue
        sections.append(
            Section(
                title="EXTERNAL RECAP / DISTILLATION",
                body=text,
                source_label=url_str,
            )
        )
    return sections


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------


def _build_header(spec: SynthInput, sections: list[Section]) -> str:
    canonical = resolve_ticker(spec.ticker)
    now = _dt.datetime.now().isoformat(timespec="seconds")
    lines = [
        SYNTH_BANNER,
        f"Ticker:   {canonical}",
        f"Period:   Q{spec.quarter} {spec.year}",
        f"Built at: {now}",
        "Sources:",
    ]
    for s in sections:
        lines.append(f"  - {s.title} ← {s.source_label}")
    lines.append("")
    return "\n".join(lines)


def _render(sections: list[Section]) -> str:
    parts: list[str] = []
    for s in sections:
        parts.append(f"\n=== {s.title} ===")
        parts.append(f"[source: {s.source_label}]")
        parts.append(s.body)
    return "\n".join(parts).strip() + "\n"


def synthesize(spec: SynthInput, force: bool = False) -> SynthResult:
    canonical = resolve_ticker(spec.ticker)
    qlabel = f"Q{spec.quarter}"
    output_path = RAW_DIR / f"{canonical}_{qlabel}_{spec.year}.txt"

    if (index_manager.has_transcript(canonical, spec.year, qlabel) or output_path.exists()):
        if not force:
            raise FileExistsError(
                f"transcript already present at {output_path}; "
                f"pass --force to overwrite"
            )
        if output_path.exists():
            output_path.unlink()

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    TMP_DIR.mkdir(parents=True, exist_ok=True)

    sections: list[Section] = []
    pr = fetch_press_release(spec)
    if pr is not None:
        sections.append(pr)
    sections.extend(ir_doc_sections(spec))
    snap = fetch_fmp_snapshot(spec)
    if snap is not None:
        sections.append(snap)
    sections.extend(fetch_recaps(spec))

    if not sections:
        raise RuntimeError(
            "no sections produced — pass at least one of "
            "--press-release-url / --press-release-pdf / --press-release-text / "
            "--ir-pdf / --recap-url (or rely on auto IR scan in micro_thesis/sources/)"
        )

    output_path.write_text(_build_header(spec, sections) + _render(sections), encoding="utf-8")

    qa_result = validate_synthesized_transcript(output_path)
    index_manager.register_transcript(
        canonical,
        spec.year,
        qlabel,
        source="synthesized_text",
        filepath=output_path.name,
        has_qa=False,  # press releases / recaps don't carry a Q&A segment
        qa_status=qa_result.status.value,
        qa_details=qa_result.model_dump(mode="json"),
    )
    if qa_result.status == QaStatus.OK:
        print(f"[done] {output_path} ({len(sections)} sections) qa=ok")
    else:
        print(
            f"[done-qa-failed] {output_path} ({len(sections)} sections) "
            f"qa=failed issues={len(qa_result.issues)}"
        )
        for issue in qa_result.issues:
            print(f"      - {issue}")
    return SynthResult(
        ticker=canonical,
        year=spec.year,
        quarter=spec.quarter,
        output_path=output_path,
        sections_written=len(sections),
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description="Synthesize a quarterly text-update transcript when no audio is available.")
    parser.add_argument("--ticker", required=True)
    parser.add_argument("--year", type=int, required=True)
    parser.add_argument("--quarter", type=int, choices=[1, 2, 3, 4], required=True)
    parser.add_argument("--press-release-url")
    parser.add_argument("--press-release-pdf", type=Path)
    parser.add_argument("--press-release-text",
                        help="Manual paste fallback when URL/PDF aren't available.")
    parser.add_argument("--recap-url", action="append", default=[],
                        help="External recap URL; pass multiple times for multiple sources.")
    parser.add_argument("--ir-pdf", action="append", default=[], type=Path,
                        help="Path to an IR PDF (investor letter, deck, supplemental). Repeatable.")
    parser.add_argument("--no-auto-ir", action="store_true",
                        help="Disable auto-scan of micro_thesis/sources/<TICKER>/ for matching IR PDFs.")
    parser.add_argument("--fmp-period-end",
                        help="Exact FMP period_end date (YYYY-MM-DD) if calendarYear/period match is unreliable.")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing transcript file.")
    args = parser.parse_args()

    spec = SynthInput(
        ticker=args.ticker,
        year=args.year,
        quarter=args.quarter,
        press_release_url=args.press_release_url,
        press_release_pdf=args.press_release_pdf,
        press_release_text=args.press_release_text,
        recap_urls=args.recap_url,
        ir_pdfs=args.ir_pdf,
        auto_ir_scan=not args.no_auto_ir,
        fmp_period_end_hint=args.fmp_period_end,
    )
    synthesize(spec, force=args.force)


if __name__ == "__main__":
    main()
