"""Per-ticker IR-document configuration for the spreadsheet KPI pipeline.

Each ticker's investor-relations site publishes a quarterly "historical data"
spreadsheet with clean numeric KPI series (one column per quarter). Unlike the
LLM-extracted brief/press-release values, these are the company's own audited
figures — so they ingest at IR_DOC tier and supersede the brief values.

A ticker's `IrConfig` declares which discovery `platform` adapter finds its
document URLs and where each canonical KPI lives in the spreadsheet (`SheetKpi`).
The `SheetKpi` map is **per-company** (every issuer's spreadsheet is laid out
differently); it is generated by `ir_pipeline.config_builder` (LLM) the first
time a ticker is refreshed and **persisted** to ``micro_thesis/ir_config/<T>.json``
— the pipeline's source of truth — rather than hand-authored. `register()` keeps
an in-memory override for tests / programmatic use.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import cast

# src/ir_pipeline/config.py → repo root is parents[2].
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_CONFIG_SUBDIR = Path("micro_thesis") / "ir_config"


@dataclass(frozen=True)
class SheetKpi:
    """Where one KPI lives in an IR historical-data spreadsheet.

    Two flavours, distinguished by ``origin`` (the capture-every-number program,
    `directives/capture_every_number_program.md`):

    * ``origin="analyst"`` (default) — a curated tier/holdings KPI. ``kpi_name``
      is the canonical ``kpi_definitions.name`` (the long ``tier_1_kpis`` form,
      e.g. "Monthly ARPAC (USD)") and is used VERBATIM so the value lands on the
      same definition the report charts read.
    * ``origin="capture"`` — an auto-mapped long-tail row. ``kpi_name`` is the
      raw spreadsheet label (cleaned); it is routed through
      ``compute.kpi_resolver.canonical_metric_name`` at INGEST time (where a live
      DB connection exists) so it joins an existing series or mints a clean new
      ``origin='capture'`` definition. Canonicalizing on write — not here — keeps
      this config conn-free and lets a capture row converge onto a series another
      extractor (S3's LLM pass) populated under the same canonical name.

    ``exact_label`` controls how ``row_label`` matches the sheet: analyst rows use
    a forgiving case-insensitive SUBSTRING match (a short hand-picked label finds
    the full cell); capture rows set ``exact_label=True`` so an auto-derived label
    matches only its own row — a bare "NII" must not also grab "Risk-adjusted NII".
    """

    kpi_name: str
    sheet: str  # worksheet title (exact)
    row_label: str  # match on the row's label cell (substring, or exact if exact_label)
    unit: str  # "percent" | "actual" | "usd" | "ratio" | "count"
    scale: float = 1.0  # multiply the raw cell (e.g. 100 for a decimal-percent row)
    origin: str = "analyst"  # "analyst" (curated) | "capture" (auto-mapped long tail)
    exact_label: bool = False  # match row_label exactly (capture rows) vs substring
    currency: str | None = None  # required for monetary rows; never inferred from ticker


@dataclass(frozen=True)
class IrConfig:
    ticker: str
    platform: str  # "mz" precise adapter | "q4cdn" generic-discovery marker
    results_center_url: str
    reporting_currency: str | None = None  # explicit workbook/config declaration only
    spreadsheet_kpis: tuple[SheetKpi, ...] = ()
    label_col: int = 1  # 0-based column holding the row labels in this issuer's sheets


# In-memory overrides (tests / programmatic). Disk is the source of truth otherwise.
_REGISTERED: dict[str, IrConfig] = {}


def register(cfg: IrConfig) -> None:
    """Register a config in memory (overrides disk for this process)."""
    _REGISTERED[cfg.ticker.upper()] = cfg


def config_path(ticker: str, repo_root: Path | None = None) -> Path:
    return (repo_root or _PROJECT_ROOT) / _CONFIG_SUBDIR / f"{ticker.upper()}.json"


def get_config(ticker: str, repo_root: Path | None = None) -> IrConfig | None:
    """Return the ticker's IrConfig — in-memory override, else the persisted JSON."""
    t = ticker.upper()
    if t in _REGISTERED:
        return _REGISTERED[t]
    path = config_path(t, repo_root)
    if path.exists():
        return _from_dict(cast("dict[str, object]", json.loads(path.read_text("utf-8"))))
    return None


def save_config(cfg: IrConfig, repo_root: Path | None = None) -> Path:
    """Persist `cfg` to micro_thesis/ir_config/<T>.json; return the path."""
    path = config_path(cfg.ticker, repo_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(_to_dict(cfg), indent=2), encoding="utf-8")
    return path


def configured_tickers(repo_root: Path | None = None) -> list[str]:
    """Tickers with a config — registered in memory or persisted on disk."""
    tickers = set(_REGISTERED)
    cfg_dir = (repo_root or _PROJECT_ROOT) / _CONFIG_SUBDIR
    if cfg_dir.exists():
        tickers.update(p.stem.upper() for p in cfg_dir.glob("*.json"))
    return sorted(tickers)


def _to_dict(cfg: IrConfig) -> dict[str, object]:
    return {
        "ticker": cfg.ticker,
        "platform": cfg.platform,
        "results_center_url": cfg.results_center_url,
        "reporting_currency": cfg.reporting_currency,
        "label_col": cfg.label_col,
        "spreadsheet_kpis": [
            {
                "kpi_name": s.kpi_name,
                "sheet": s.sheet,
                "row_label": s.row_label,
                "unit": s.unit,
                "currency": s.currency,
                "scale": s.scale,
                "origin": s.origin,
                "exact_label": s.exact_label,
            }
            for s in cfg.spreadsheet_kpis
        ],
    }


def _from_dict(d: dict[str, object]) -> IrConfig:
    candidate = d.get("spreadsheet_kpis")
    kpis: list[SheetKpi] = []
    if isinstance(candidate, list):
        raw = cast("list[object]", candidate)
        for item in raw:
            if not isinstance(item, dict):
                continue
            k = cast("dict[str, object]", item)
            kpis.append(
                SheetKpi(
                    kpi_name=str(k["kpi_name"]),
                    sheet=str(k["sheet"]),
                    row_label=str(k["row_label"]),
                    unit=str(k.get("unit", "actual")),
                    currency=(str(k["currency"]) if k.get("currency") is not None else None),
                    scale=float(cast("float", k.get("scale", 1.0))),
                    # Back-compat: a pre-capture config (e.g. the hand-built NU.json)
                    # has neither field — default to a curated analyst row matched by
                    # substring, preserving its original behavior exactly.
                    origin=str(k.get("origin", "analyst")),
                    exact_label=bool(k.get("exact_label", False)),
                )
            )
    return IrConfig(
        ticker=str(d["ticker"]),
        platform=str(d["platform"]),
        results_center_url=str(d.get("results_center_url", "")),
        reporting_currency=(
            str(d["reporting_currency"]) if d.get("reporting_currency") is not None else None
        ),
        spreadsheet_kpis=tuple(kpis),
        label_col=int(cast("int", d.get("label_col", 1))),
    )
