"""Tests for the per-name growth-fade curvature calibration
(``src/dcf/fade_calibration.py``): the convex-fade projection mirror and the
consensus-fit solver (recovery of a known curvature, near-term weighting, the
linear floor, and the < 2-point fallback)."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from dcf import fade_calibration as fc  # noqa: E402

N_FC = 10
_BASE = {"A": 600.0, "B": 400.0}
_NEAR = {"A": 0.30, "B": 0.20}
_TERM = {"A": 0.05, "B": 0.04}


def test_projection_year_one_is_base_times_near_growth() -> None:
    proj = fc.project_total_revenue(_BASE, _NEAR, _TERM, curvature=2.0, n_offsets=1, n_fc=N_FC)
    # Year 0 (first forecast year) grows each segment at its NEAR rate regardless of p.
    assert proj[0] == pytest.approx(600.0 * 1.30 + 400.0 * 1.20)


def test_projection_curvature_independent_at_year_one() -> None:
    a = fc.project_total_revenue(_BASE, _NEAR, _TERM, 1.0, 1, N_FC)[0]
    b = fc.project_total_revenue(_BASE, _NEAR, _TERM, 3.5, 1, N_FC)[0]
    assert a == pytest.approx(b)


def test_higher_curvature_lowers_midhorizon_revenue() -> None:
    """A more convex fade decelerates faster after year 1, so cumulative revenue by
    year 5 is lower."""
    lo = fc.project_total_revenue(_BASE, _NEAR, _TERM, 1.0, 6, N_FC)[-1]
    hi = fc.project_total_revenue(_BASE, _NEAR, _TERM, 3.0, 6, N_FC)[-1]
    assert hi < lo


def test_calibration_recovers_a_known_curvature() -> None:
    """Consensus generated by a known p=2.5 path is best-fit by ~2.5."""
    true_p = 2.5
    n = 5
    proj = fc.project_total_revenue(_BASE, _NEAR, _TERM, true_p, n, N_FC)
    consensus = {j: proj[j] for j in range(n)}
    fit = fc.calibrate_curvature(_BASE, _NEAR, _TERM, consensus, N_FC)
    assert fit == pytest.approx(true_p, abs=0.1)


def test_calibration_returns_default_when_too_few_points() -> None:
    assert fc.calibrate_curvature(_BASE, _NEAR, _TERM, {0: 1300.0}, N_FC) == fc.DEFAULT_CURVATURE
    assert fc.calibrate_curvature(_BASE, _NEAR, _TERM, {}, N_FC) == fc.DEFAULT_CURVATURE


def test_calibration_respects_bounds() -> None:
    # A consensus path implying very fast deceleration still clamps at the ceiling.
    fast = {0: 1300.0, 1: 1320.0, 2: 1330.0, 3: 1335.0, 4: 1338.0}
    fit = fc.calibrate_curvature(_BASE, _NEAR, _TERM, fast, N_FC)
    assert fc.CURVATURE_BOUNDS[0] <= fit <= fc.CURVATURE_BOUNDS[1]


def test_calibration_never_goes_below_linear_floor() -> None:
    """Even a consensus path implying sustained (concave) growth floors at 1.0 —
    the engine never fades MORE gently than linear, so the tail can't re-inflate."""
    sustained = {
        j: fc.project_total_revenue(_BASE, _NEAR, _TERM, 1.0, 5, N_FC)[j] * 1.5 for j in range(5)
    }
    fit = fc.calibrate_curvature(_BASE, _NEAR, _TERM, sustained, N_FC)
    assert fit >= 1.0


def test_near_term_weighting_holds_fit_closer_to_near_years() -> None:
    """On a path whose near years imply p=2.0 but whose FAR year is distorted,
    near-term weighting keeps the fit closer to the near-implied 2.0 than uniform
    weighting (which chases the distorted far year)."""
    n = 5
    base_path = fc.project_total_revenue(_BASE, _NEAR, _TERM, 2.0, n, N_FC)
    consensus = {j: base_path[j] for j in range(n)}
    consensus[n - 1] *= 1.15  # mild far-year distortion
    near_fit = fc.calibrate_curvature(_BASE, _NEAR, _TERM, consensus, N_FC, near_weight_decay=0.6)
    flat_fit = fc.calibrate_curvature(_BASE, _NEAR, _TERM, consensus, N_FC, near_weight_decay=1.0)
    # Near-weighting sits at least as close to the near-years' p=2.0 as uniform does.
    assert abs(near_fit - 2.0) <= abs(flat_fit - 2.0)
