"""Tests for src/transcripts/source_reliability.py — the reliability ranking
that backs the ingest-time period-conflict guard."""

from __future__ import annotations

from pathlib import Path

from transcripts.source_reliability import (
    IR_TRANSCRIPT_DOC,
    MANUAL_PDF,
    UNKNOWN_LEGACY,
    choose_winner,
    classify_transcript_source,
    reliability_rank,
)


def _synth_text(source_name: str) -> str:
    return (
        "=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===\n"
        "Generated by execution/fetch_qa_transcript.py from a free aggregator.\n"
        "\n"
        "Ticker:    NVDA\n"
        "Period:    Q1 2026\n"
        f"Source:    aggregator_{source_name} (https://example.com/x)\n"
        "\n"
        "=== Q&A SEGMENT ===\n"
        "Operator: first question...\n"
    )


def test_classify_ir_transcript_doc_type_wins_regardless_of_content() -> None:
    assert (
        classify_transcript_source(
            Path("whatever.pdf"), "no banner here", is_ir_transcript_doc=True
        )
        == IR_TRANSCRIPT_DOC
    )


def test_classify_reads_banner_source_line() -> None:
    assert (
        classify_transcript_source(Path("transcripts/raw/NVDA_Q1_2026.txt"), _synth_text("roic"))
        == "aggregator_roic"
    )
    assert (
        classify_transcript_source(
            Path("transcripts/raw/NVDA_Q1_2026.txt"), _synth_text("issuer_ir")
        )
        == "aggregator_issuer_ir"
    )
    assert (
        classify_transcript_source(
            Path("transcripts/raw/NVDA_Q1_2026.txt"), _synth_text("stockanalysis")
        )
        == "aggregator_stockanalysis"
    )


def test_classify_pdf_extension_is_manual_when_no_banner() -> None:
    assert (
        classify_transcript_source(
            Path("transcripts/processed/NVDA_Q1_2026.pdf"), "plain text body"
        )
        == MANUAL_PDF
    )


def test_classify_txt_with_no_banner_falls_back_to_index_hint() -> None:
    assert (
        classify_transcript_source(
            Path("transcripts/raw/NVDA_Q1_2026.txt"),
            "plain whisper transcript text",
            index_hint="yt_dlp_whisper_url",
        )
        == "yt_dlp_whisper_url"
    )


def test_classify_txt_with_no_banner_and_no_hint_is_unknown_legacy() -> None:
    assert (
        classify_transcript_source(Path("transcripts/raw/NVDA_Q1_2026.txt"), "plain text, no clues")
        == UNKNOWN_LEGACY
    )


def test_reliability_rank_ordering_matches_evidence() -> None:
    # Full-call/official sources outrank Q&A-only aggregators; roic,
    # stockanalysis, and tickertrends are all DOM-verified per-turn parses
    # as of 2026-07-25 (src/aggregator_sources.py) — equal tier, none still
    # on the old flatten-and-guess heuristic.
    assert reliability_rank(IR_TRANSCRIPT_DOC) > reliability_rank(MANUAL_PDF)
    assert reliability_rank(MANUAL_PDF) > reliability_rank("yt_dlp_whisper_url")
    assert reliability_rank("yt_dlp_whisper_url") > reliability_rank("yt_dlp_whisper_search")
    assert reliability_rank("yt_dlp_whisper_search") > reliability_rank("aggregator_issuer_ir")
    assert reliability_rank("aggregator_issuer_ir") > reliability_rank("aggregator_roic")
    assert reliability_rank("aggregator_roic") == reliability_rank("aggregator_stockanalysis")
    assert reliability_rank("aggregator_stockanalysis") == reliability_rank(
        "aggregator_tickertrends"
    )
    assert reliability_rank("aggregator_tickertrends") > reliability_rank(UNKNOWN_LEGACY)
    assert reliability_rank(UNKNOWN_LEGACY) > reliability_rank("something_never_seen")
    assert reliability_rank(None) == reliability_rank("something_never_seen")


def test_choose_winner_higher_tier_wins_even_with_fewer_segments() -> None:
    """The GOOG Q1 2025 real-world case: a 7-segment manual PDF (full call,
    64k chars) must beat a 22-segment Q&A-only aggregator scrape."""
    assert choose_winner(
        new_source=MANUAL_PDF,
        new_segment_count=7,
        old_source="aggregator_roic",
        old_segment_count=22,
    )
    assert not choose_winner(
        new_source="aggregator_roic",
        new_segment_count=22,
        old_source=MANUAL_PDF,
        old_segment_count=7,
    )


def test_choose_winner_same_tier_falls_back_to_segment_count() -> None:
    assert choose_winner(
        new_source="aggregator_roic",
        new_segment_count=34,
        old_source="aggregator_roic",
        old_segment_count=1,
    )
    assert not choose_winner(
        new_source="aggregator_roic",
        new_segment_count=1,
        old_source="aggregator_roic",
        old_segment_count=34,
    )


def test_choose_winner_same_tier_same_segments_is_not_a_replace() -> None:
    """A strict '>' means a genuine tie never triggers churn."""
    assert not choose_winner(
        new_source="aggregator_roic",
        new_segment_count=10,
        old_source="aggregator_roic",
        old_segment_count=10,
    )


def test_choose_winner_treats_missing_old_source_as_unknown_legacy() -> None:
    assert choose_winner(
        new_source=MANUAL_PDF, new_segment_count=1, old_source=None, old_segment_count=100
    )
