"""Tests for the reliability-ranked period-level idempotency guard added to
`ingest_one` / `ingest_existing_ir_transcript` (src/compute/transcript_ingest.py)
after the 2026-07-25 transcript-duplication incident: two different documents
may retain multiple immutable versions, but exactly one is current for a
(ticker, fiscal_period_type, period_end).
"""

from __future__ import annotations

import sqlite3
from datetime import datetime
from pathlib import Path

from compute.transcript_ingest import (
    SpeakerTurn,
    find_transcript_for_period,
    ingest_one,
    insert_document,
    insert_segments,
    insert_transcript,
)
from models.facts import FiscalPeriodType


def _conn() -> sqlite3.Connection:
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(
        """
        CREATE TABLE documents (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ticker TEXT NOT NULL,
            source_type TEXT NOT NULL,
            doc_type TEXT NOT NULL,
            period_start TIMESTAMP,
            period_end TIMESTAMP,
            file_path TEXT NOT NULL,
            sha256 TEXT NOT NULL UNIQUE,
            fetched_at TIMESTAMP NOT NULL,
            fetch_status TEXT NOT NULL,
            http_code INTEGER,
            raw_bytes_size INTEGER NOT NULL,
            source_url TEXT,
            parent_document_id INTEGER
        );
        CREATE TABLE transcripts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            document_id INTEGER NOT NULL UNIQUE,
            ticker TEXT NOT NULL,
            call_date TIMESTAMP,
            fiscal_period_type TEXT,
            period_end TIMESTAMP,
            source_url TEXT,
            has_qa_section INTEGER,
            source TEXT,
            version_number INTEGER NOT NULL DEFAULT 1,
            is_current INTEGER NOT NULL DEFAULT 1,
            recorded_at TIMESTAMP,
            superseded_at TIMESTAMP,
            superseded_by_transcript_id INTEGER
        );
        CREATE TABLE transcript_segments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcript_id INTEGER NOT NULL,
            seq INTEGER NOT NULL,
            speaker TEXT,
            speaker_role TEXT,
            time_code_start TEXT,
            time_code_end TEXT,
            text TEXT NOT NULL
        );
        CREATE UNIQUE INDEX uq_transcripts_current_ticker_period_type_end
            ON transcripts(ticker, fiscal_period_type, period_end)
            WHERE is_current = 1;
        """
    )
    return c


def _seed_transcript(
    conn: sqlite3.Connection,
    project_root: Path,
    *,
    ticker: str,
    period_end: datetime,
    fiscal_period_type: FiscalPeriodType,
    source: str,
    segment_count: int,
    file_name: str,
) -> tuple[int, int]:
    """Seed an existing (document, transcript, segments) trio; returns (document_id, transcript_id)."""
    file_path = project_root / "transcripts" / "processed" / file_name
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(f"seed content for {file_name}", encoding="utf-8")
    doc_id = insert_document(
        conn,
        ticker=ticker,
        file_path=file_path,
        sha256=f"seed-sha-{file_name}",
        period_end=period_end,
        project_root=project_root,
    )
    transcript_id = insert_transcript(
        conn,
        document_id=doc_id,
        ticker=ticker,
        fiscal_period_type=fiscal_period_type,
        period_end=period_end,
        source=source,
    )
    insert_segments(
        conn,
        transcript_id=transcript_id,
        turns=[SpeakerTurn(speaker="Speaker", text="turn") for _ in range(segment_count)],
    )
    conn.commit()
    return doc_id, transcript_id


def _write_pdf_like_txt(project_root: Path, rel: str, body: str) -> Path:
    """A .txt file with real multi-turn content (not a .pdf — tests exercise
    the aggregator/whisper path, which never writes .pdf)."""
    path = project_root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path


_SYNTH_ROIC_BODY = (
    "=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===\n"
    "Generated by execution/fetch_qa_transcript.py from a free aggregator.\n"
    "\n"
    "Ticker:    NVDA\n"
    "Period:    Q1 2025\n"
    "Source:    aggregator_roic (https://example.com/x)\n"
    "\n"
    "=== Q&A SEGMENT ===\n"
    "Operator\nFirst question.\n\nAnalyst One\nQuestion text here.\n\n"
    "Operator\nNext question.\n\nAnalyst Two\nAnother question here.\n"
)

_SYNTH_STOCKANALYSIS_BODY = _SYNTH_ROIC_BODY.replace("aggregator_roic", "aggregator_stockanalysis")


def test_no_conflict_inserts_normally(tmp_path: Path) -> None:
    conn = _conn()
    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", _SYNTH_ROIC_BODY)

    result = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )

    assert result is not None
    assert not result.skipped_existing
    assert result.source == "aggregator_roic"
    assert conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0] == 1
    assert conn.execute("SELECT COUNT(*) FROM transcripts").fetchone()[0] == 1


def test_higher_tier_existing_row_wins_and_new_version_is_preserved(tmp_path: Path) -> None:
    """The NVDA-shaped real-world case: a manual PDF already on file must not
    be replaced by a fresh Q&A-only aggregator scrape, and the scrape must
    preserve the lower-ranked fetch as a linked historical version."""
    conn = _conn()
    old_doc_id, old_transcript_id = _seed_transcript(
        conn,
        tmp_path,
        ticker="NVDA",
        period_end=datetime(2025, 3, 31),
        fiscal_period_type=FiscalPeriodType.Q1,
        source="manual_pdf",
        segment_count=7,
        file_name="NVDA_Q1_2025.pdf",
    )

    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", _SYNTH_ROIC_BODY)
    result = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )

    assert result is not None
    assert result.skipped_existing
    assert result.document_id == old_doc_id
    assert result.transcript_id == old_transcript_id
    assert conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0] == 2
    historical = conn.execute(
        "SELECT is_current, superseded_by_transcript_id FROM transcripts WHERE id <> ?",
        (old_transcript_id,),
    ).fetchone()
    assert tuple(historical) == (0, old_transcript_id)
    # The pre-existing winner is untouched.
    assert (
        conn.execute(
            "SELECT source FROM transcripts WHERE id = ?", (old_transcript_id,)
        ).fetchone()[0]
        == "manual_pdf"
    )


def test_lower_tier_existing_row_is_preserved_as_superseded(tmp_path: Path) -> None:
    """An old row with unrecoverable provenance (pre-dates the `source`
    column) must yield to a freshly-classified aggregator fetch for the
    same period."""
    conn = _conn()
    old_doc_id, old_transcript_id = _seed_transcript(
        conn,
        tmp_path,
        ticker="NVDA",
        period_end=datetime(2025, 3, 31),
        fiscal_period_type=FiscalPeriodType.Q1,
        source="unknown_legacy",
        segment_count=1,
        file_name="NVDA_Q1_2025_old.txt",
    )

    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", _SYNTH_ROIC_BODY)

    result = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )

    assert result is not None
    assert not result.skipped_existing
    assert result.source == "aggregator_roic"
    assert conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0] == 2
    assert conn.execute("SELECT COUNT(*) FROM transcripts").fetchone()[0] == 2
    old = conn.execute(
        "SELECT is_current, superseded_at, superseded_by_transcript_id "
        "FROM transcripts WHERE id = ?",
        (old_transcript_id,),
    ).fetchone()
    assert tuple(old) == (0, old["superseded_at"], result.transcript_id)
    assert old["superseded_at"] is not None
    assert (
        conn.execute(
            "SELECT COUNT(*) FROM transcript_segments WHERE transcript_id = ?",
            (old_transcript_id,),
        ).fetchone()[0]
        == 1
    )
    assert (
        conn.execute("SELECT COUNT(*) FROM documents WHERE id = ?", (old_doc_id,)).fetchone()[0]
        == 1
    )


def test_same_tier_richer_fetch_supersedes_thin_stub(tmp_path: Path) -> None:
    """Same-source re-fetch that recovers real multi-turn content (e.g. the
    2026-07-25 roic DOM fix) replaces an old single-blob row from the same
    tier."""
    conn = _conn()
    old_doc_id, _old_transcript_id = _seed_transcript(
        conn,
        tmp_path,
        ticker="NVDA",
        period_end=datetime(2025, 3, 31),
        fiscal_period_type=FiscalPeriodType.Q1,
        source="aggregator_roic",
        segment_count=1,
        file_name="NVDA_Q1_2025_stub.txt",
    )

    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", _SYNTH_ROIC_BODY)

    result = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )

    assert result is not None
    assert not result.skipped_existing
    assert (
        conn.execute("SELECT COUNT(*) FROM documents WHERE id = ?", (old_doc_id,)).fetchone()[0]
        == 1
    )
    assert (
        conn.execute(
            "SELECT is_current FROM transcripts WHERE document_id = ?", (old_doc_id,)
        ).fetchone()[0]
        == 0
    )
    # banner+header preamble (anonymous turn) + Operator/Analyst One/Operator/Analyst Two
    assert result.segment_count == 5


def test_same_tier_thinner_fetch_is_skipped(tmp_path: Path) -> None:
    """A re-fetch that's still degenerate (1 segment) must not replace an
    already-good same-tier row — this is the DHR Q2 2026 real-world case."""
    conn = _conn()
    old_doc_id, old_transcript_id = _seed_transcript(
        conn,
        tmp_path,
        ticker="NVDA",
        period_end=datetime(2025, 3, 31),
        fiscal_period_type=FiscalPeriodType.Q1,
        source="aggregator_roic",
        segment_count=4,
        file_name="NVDA_Q1_2025_good.txt",
    )

    thin_body = (
        "=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===\n"
        "Source:    aggregator_roic (https://example.com/x)\n"
        "\n=== Q&A SEGMENT ===\nOne giant unsegmented blob of text.\n"
    )
    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", thin_body)

    result = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )

    assert result is not None
    assert result.skipped_existing
    assert result.document_id == old_doc_id
    assert result.transcript_id == old_transcript_id
    assert conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0] == 2
    assert conn.execute("SELECT COUNT(*) FROM transcripts WHERE is_current = 1").fetchone()[0] == 1
    assert conn.execute("SELECT COUNT(*) FROM transcripts WHERE is_current = 0").fetchone()[0] == 1


def test_find_transcript_for_period_none_when_absent(tmp_path: Path) -> None:
    conn = _conn()
    assert (
        find_transcript_for_period(
            conn,
            ticker="NVDA",
            fiscal_period_type=FiscalPeriodType.Q1,
            period_end=datetime(2025, 3, 31),
        )
        is None
    )


def test_byte_identical_refetch_still_short_circuits_before_the_guard(tmp_path: Path) -> None:
    """Unchanged behavior: a true byte-identical re-fetch is a sha256 no-op
    and never reaches the period guard at all."""
    conn = _conn()
    raw_path = _write_pdf_like_txt(tmp_path, "transcripts/raw/NVDA_Q1_2025.txt", _SYNTH_ROIC_BODY)

    first = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )
    assert first is not None and not first.skipped_existing

    second = ingest_one(
        conn, file_path=raw_path, project_root=tmp_path, tracked_tickers=frozenset({"NVDA"})
    )
    assert second is not None
    assert second.skipped_existing
    assert second.document_id == first.document_id
    assert second.transcript_id == first.transcript_id
    assert conn.execute("SELECT COUNT(*) FROM documents").fetchone()[0] == 1
