"""Tests for §5 Earnings — cross-quarter themes split (prepared vs Q&A).

Covers:
  - the transcript splitter's detection ladder (aggregator banner, CallStreet
    header, has_qa_section fallback)
  - the LLM-response parser (well-formed JSON, fence-stripped JSON, malformed)
  - the builder end-to-end with mocked LLM:
      * mixed has_qa_section flags → both sides populate
      * no Q&A across the window → fallback note + prepared-only
      * no prepared across the window → fallback note + Q&A-only
  - the markdown + HTML renderers' theme blocks

Mocking strategy: the LLM call goes through llm_client.extract_qa_vs_prepared_themes,
which we monkeypatch on the EARNINGS section's import name (it imports the
function lazily inside _build_themes) so the test doesn't need a real Claude CLI.
"""

from __future__ import annotations

import json
import sqlite3
from io import StringIO
from pathlib import Path
from typing import Any

import pytest

from report.models import EarningsSection, QuoteSnippet, SectionStatus, ThemeRollup
from report.renderers.html import _earnings as html_earnings
from report.renderers.markdown import _earnings as md_earnings
from report.sections import earnings as earnings_section
from report.sections.earnings import (
    _parse_themes_response,
    _split_transcript_sections,
    build,
)

# ---------------------------------------------------------------------------
# Splitter
# ---------------------------------------------------------------------------


def test_split_aggregator_qa_only_banner_returns_qa_only() -> None:
    text = """=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===
Generated by execution/fetch_qa_transcript.py from a free aggregator.

Ticker: GOOG
Period: Q1 2026

=== Q&A SEGMENT ===
first question comes from Brian Nowak.

B Brian Nowak: How are you thinking about CapEx?
"""
    prepared, qa = _split_transcript_sections(text, has_qa_flag=True)
    assert prepared is None
    assert qa is not None
    assert "Brian Nowak" in qa
    # Metadata preamble should not leak into the QA body
    assert "SYNTHESIZED" not in qa


def test_split_callstreet_header_separates_sides() -> None:
    text = """Acme Corp Q1 2026 Earnings Call

MANAGEMENT DISCUSSION SECTION

Operator: Welcome to the Q1 call.
Jane Doe (CEO): Revenue grew 20%, margins expanded.

QUESTION AND ANSWER SECTION

Brian Nowak (Morgan Stanley): How does the trajectory look?
Jane Doe: We expect continued growth.
"""
    prepared, qa = _split_transcript_sections(text, has_qa_flag=True)
    assert prepared is not None
    assert "Jane Doe (CEO)" in prepared
    assert "Brian Nowak" not in prepared
    assert qa is not None
    assert "Brian Nowak" in qa
    assert "Jane Doe (CEO)" not in qa


def test_split_no_markers_qa_flag_true_returns_qa_only() -> None:
    """When the file carries no recognizable section markers but the DB flag
    says Q&A is present, treat the entire file as Q&A (don't lose content)."""
    text = "Just some text without markers. Brian: question. Mgmt: answer."
    prepared, qa = _split_transcript_sections(text, has_qa_flag=True)
    assert prepared is None
    assert qa is not None and "Brian" in qa


def test_split_operator_first_question_phrase_separates_sides() -> None:
    """Free-form full transcripts often lack an explicit Q&A header but
    transition via "first question comes from X" — the splitter should
    detect that and treat the preceding text as prepared remarks."""
    text = (
        "Operator: Welcome to the Q1 call.\n"
        "CEO: Revenue grew 20%, margins expanded.\n"
        "CFO: Capex was $5B this quarter, $25B for the year.\n\n"
        "Operator: Our first question comes from Brian Nowak at Morgan Stanley.\n"
        "Brian Nowak: How are you thinking about TPU sales?\n"
        "CEO: Opportunistic, ROIC framework.\n"
    )
    prepared, qa = _split_transcript_sections(text, has_qa_flag=True)
    assert prepared is not None
    assert "Revenue grew 20%" in prepared
    assert "Brian Nowak" not in prepared
    assert qa is not None
    assert "Brian Nowak" in qa
    assert "TPU sales" in qa


def test_split_no_markers_qa_flag_false_returns_prepared_only() -> None:
    text = "Operator: Welcome. CEO: Revenue grew 20%. CFO: Margins expanded."
    prepared, qa = _split_transcript_sections(text, has_qa_flag=False)
    assert qa is None
    assert prepared is not None and "Revenue grew 20%" in prepared


def test_split_no_markers_qa_flag_none_returns_prepared() -> None:
    """Unknown DB state + no markers → conservative default of prepared."""
    text = "Some random earnings call content with no Q&A signals."
    prepared, qa = _split_transcript_sections(text, has_qa_flag=None)
    assert qa is None
    assert prepared is not None


def test_split_empty_text_returns_none_none() -> None:
    prepared, qa = _split_transcript_sections("", has_qa_flag=None)
    assert prepared is None
    assert qa is None


# ---------------------------------------------------------------------------
# Response parser
# ---------------------------------------------------------------------------


def test_parse_themes_response_well_formed() -> None:
    raw = json.dumps(
        {
            "prepared_themes": [
                {
                    "theme_name": "CapEx trajectory",
                    "mentions_per_quarter": {"Q4 2025": 2, "Q1 2026": 3},
                    "evidence": [
                        {"period": "Q1 2026", "speaker": "Anat", "text": "CapEx will increase significantly."}
                    ],
                }
            ],
            "qa_themes": [
                {
                    "theme_name": "AI compute capacity",
                    "mentions_per_quarter": {"Q1 2026": 4},
                    "evidence": [
                        {"period": "Q1 2026", "speaker": "Brian (MS)", "text": "Help us think about TPUs."}
                    ],
                }
            ],
        }
    )
    prepared, qa = _parse_themes_response(raw)
    assert len(prepared) == 1
    assert prepared[0].theme_name == "CapEx trajectory"
    assert prepared[0].mentions_per_quarter == {"Q4 2025": 2, "Q1 2026": 3}
    # last_4q_count derived from sum when LLM omits it
    assert prepared[0].last_4q_count == 5
    assert prepared[0].evidence[0].speaker == "Anat"
    assert len(qa) == 1
    assert qa[0].theme_name == "AI compute capacity"


def test_parse_themes_response_strips_markdown_fence() -> None:
    raw = '```json\n{"prepared_themes": [], "qa_themes": []}\n```'
    prepared, qa = _parse_themes_response(raw)
    assert prepared == []
    assert qa == []


def test_parse_themes_response_malformed_returns_empty() -> None:
    prepared, qa = _parse_themes_response("not valid json")
    assert prepared == []
    assert qa == []


def test_parse_themes_response_honors_explicit_last_4q_count() -> None:
    raw = json.dumps(
        {
            "prepared_themes": [
                {
                    "theme_name": "X",
                    "last_4q_count": 7,  # explicit; differs from mentions sum
                    "mentions_per_quarter": {"Q1 2026": 1, "Q4 2025": 1},
                    "evidence": [],
                }
            ],
            "qa_themes": [],
        }
    )
    prepared, _ = _parse_themes_response(raw)
    assert prepared[0].last_4q_count == 7


# ---------------------------------------------------------------------------
# Builder — end-to-end with monkeypatched LLM + on-disk fixtures
# ---------------------------------------------------------------------------


def _seed_transcripts_dir(repo_root: Path, ticker: str, quarters: list[tuple[int, int, str]]) -> None:
    """Write transcripts/processed/<TICKER>_Q<n>_<Y>.txt files with given content."""
    d = repo_root / "transcripts" / "processed"
    d.mkdir(parents=True, exist_ok=True)
    for q, y, content in quarters:
        (d / f"{ticker}_Q{q}_{y}.txt").write_text(content, encoding="utf-8")


def _seed_transcripts_db(repo_root: Path, ticker: str, rows: list[tuple[int, int, bool | None]]) -> None:
    """Seed a minimal portfolio.db with transcripts rows carrying has_qa_section flags.

    Also creates an empty `earnings_surprises` table so the §6 surprise-card
    builder (which fires unconditionally inside `build`) doesn't error out
    on a missing table — it tolerates an empty result set but not a missing
    schema.
    """
    db_dir = repo_root / "data"
    db_dir.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_dir / "portfolio.db")
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS transcripts (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            document_id INTEGER,
            ticker TEXT NOT NULL,
            call_date TEXT,
            fiscal_period_type TEXT NOT NULL,
            period_end TEXT NOT NULL,
            source_url TEXT,
            has_qa_section INTEGER
        );
        CREATE TABLE IF NOT EXISTS earnings_surprises (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            ticker TEXT NOT NULL,
            release_date TEXT NOT NULL,
            eps_surprise_pct NUMERIC,
            revenue_surprise_pct NUMERIC,
            source_name TEXT NOT NULL,
            fetched_at TEXT NOT NULL
        );
        """
    )
    for q, y, flag in rows:
        # period_end's year prefix is what _load_has_qa_flags matches against
        pe = f"{y}-{3 * q:02d}-30"
        conn.execute(
            "INSERT INTO transcripts (ticker, fiscal_period_type, period_end, has_qa_section) "
            "VALUES (?, ?, ?, ?)",
            (ticker, f"Q{q}", pe, None if flag is None else int(flag)),
        )
    conn.commit()
    conn.close()


def _aggregator_qa(period: str, body: str) -> str:
    return (
        f"=== SYNTHESIZED QUARTERLY UPDATE — Q&A SEGMENT ONLY ===\n"
        f"Period: {period}\n\n=== Q&A SEGMENT ===\n{body}\n"
    )


def _callstreet_full(prepared: str, qa: str) -> str:
    return (
        f"MANAGEMENT DISCUSSION SECTION\n\n{prepared}\n\n"
        f"QUESTION AND ANSWER SECTION\n\n{qa}\n"
    )


def _mock_themes_response(prepared: list[dict[str, Any]], qa: list[dict[str, Any]]) -> str:
    return json.dumps({"prepared_themes": prepared, "qa_themes": qa})


def test_build_themes_mixed_qa_flags_populates_both_sides(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    ticker = "ACME"
    # Two aggregator (Q&A-only) + two CallStreet-full transcripts in the 4Q window.
    _seed_transcripts_dir(
        repo,
        ticker,
        [
            (2, 2025, _aggregator_qa("Q2 2025", "B Brian: question about cloud.")),
            (3, 2025, _aggregator_qa("Q3 2025", "B Brian: another cloud question.")),
            (4, 2025, _callstreet_full(
                "Operator: welcome. CEO: revenue grew 20%, margins expanded.",
                "Analyst: TPU pricing? CFO: opportunistic."
            )),
            (1, 2026, _callstreet_full(
                "CEO: Q1 was strong, GCP up 35%.",
                "Analyst: Capex 2027? Anat: it will increase significantly."
            )),
        ],
    )
    _seed_transcripts_db(
        repo,
        ticker,
        [
            (2, 2025, True),
            (3, 2025, True),
            (4, 2025, True),
            (1, 2026, True),
        ],
    )

    called_with: dict[str, Any] = {}

    def fake_extractor(ticker_arg: str, transcripts_arg: list[dict[str, Any]]) -> str:
        called_with["ticker"] = ticker_arg
        called_with["transcripts"] = transcripts_arg
        return _mock_themes_response(
            prepared=[
                {
                    "theme_name": "Margin expansion narrative",
                    "mentions_per_quarter": {"Q4 2025": 1, "Q1 2026": 1},
                    "evidence": [
                        {"period": "Q4 2025", "speaker": "CEO", "text": "Margins expanded."}
                    ],
                }
            ],
            qa=[
                {
                    "theme_name": "Capex trajectory",
                    "mentions_per_quarter": {"Q1 2026": 1, "Q4 2025": 1},
                    "evidence": [
                        {"period": "Q1 2026", "speaker": "Analyst", "text": "Capex 2027?"}
                    ],
                }
            ],
        )

    # The builder imports lazily — patch on the llm_client module instead.
    import llm_client

    monkeypatch.setattr(llm_client, "extract_qa_vs_prepared_themes", fake_extractor)

    section = build(ticker, repo, enable_llm=True)

    assert called_with["ticker"] == ticker
    # 4 transcripts in the window, all surfaced to the extractor
    assert len(called_with["transcripts"]) == 4
    # Aggregator quarters carry prepared=None, qa=text
    aggregator_entries = [t for t in called_with["transcripts"] if t["prepared"] is None]
    assert len(aggregator_entries) == 2
    # CallStreet quarters carry both sides
    full_entries = [t for t in called_with["transcripts"] if t["prepared"] and t["qa"]]
    assert len(full_entries) == 2

    assert len(section.prepared_remarks_themes) == 1
    assert section.prepared_remarks_themes[0].theme_name == "Margin expansion narrative"
    assert len(section.qa_themes) == 1
    assert section.qa_themes[0].theme_name == "Capex trajectory"
    # No fallback note when both sides have content
    assert section.themes_note is None


def test_build_themes_no_qa_falls_back_to_prepared_only_with_note(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    ticker = "PREP"
    # All 4 transcripts are prepared-remarks only (no Q&A in any of them).
    # has_qa_section = False on every row.
    _seed_transcripts_dir(
        repo,
        ticker,
        [
            (2, 2025, "Operator: welcome. CEO: revenue grew 20%."),
            (3, 2025, "Operator: welcome. CEO: Q3 was strong."),
            (4, 2025, "Operator: welcome. CEO: Margins expanded."),
            (1, 2026, "Operator: welcome. CEO: Q1 print was good."),
        ],
    )
    _seed_transcripts_db(
        repo,
        ticker,
        [
            (2, 2025, False),
            (3, 2025, False),
            (4, 2025, False),
            (1, 2026, False),
        ],
    )

    def fake_extractor(ticker_arg: str, transcripts_arg: list[dict[str, Any]]) -> str:
        # Verify the extractor sees prepared on every entry, qa nowhere
        assert all(t["prepared"] for t in transcripts_arg)
        assert all(t["qa"] is None for t in transcripts_arg)
        return _mock_themes_response(
            prepared=[
                {
                    "theme_name": "Top-line growth framing",
                    "mentions_per_quarter": {"Q2 2025": 1, "Q4 2025": 1},
                    "evidence": [],
                }
            ],
            qa=[],  # well-behaved LLM returns empty for the missing side
        )

    import llm_client

    monkeypatch.setattr(llm_client, "extract_qa_vs_prepared_themes", fake_extractor)

    section = build(ticker, repo, enable_llm=True)

    assert section.prepared_remarks_themes
    assert section.qa_themes == []
    assert section.themes_note is not None
    assert "Q&A" in section.themes_note


def test_build_themes_defensively_drops_qa_themes_when_no_source_qa(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """If the LLM ignores the empty-side instruction and returns qa themes
    anyway, the builder forces them to [] because we know there was no
    source material to ground them in."""
    repo = tmp_path / "repo"
    repo.mkdir()
    ticker = "STRICT"
    _seed_transcripts_dir(repo, ticker, [(1, 2026, "Operator: welcome. CEO: Q1 was good.")])
    _seed_transcripts_db(repo, ticker, [(1, 2026, False)])

    def fake_extractor(_t: str, _x: list[dict[str, Any]]) -> str:
        return _mock_themes_response(
            prepared=[
                {"theme_name": "P", "mentions_per_quarter": {"Q1 2026": 1}, "evidence": []}
            ],
            qa=[
                {"theme_name": "Made-up QA theme", "mentions_per_quarter": {"Q1 2026": 1}, "evidence": []}
            ],
        )

    import llm_client

    monkeypatch.setattr(llm_client, "extract_qa_vs_prepared_themes", fake_extractor)

    section = build(ticker, repo, enable_llm=True)
    assert section.prepared_remarks_themes
    assert section.qa_themes == [], "qa themes must be force-dropped when no Q&A source material exists"


def test_build_themes_disabled_when_enable_llm_false(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    ticker = "OFF"
    _seed_transcripts_dir(repo, ticker, [(1, 2026, _aggregator_qa("Q1 2026", "B: question."))])
    _seed_transcripts_db(repo, ticker, [(1, 2026, True)])

    section = build(ticker, repo, enable_llm=False)
    assert section.prepared_remarks_themes == []
    assert section.qa_themes == []
    assert section.themes_note is None


def test_build_themes_uses_cache_on_second_call(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    ticker = "CACHE"
    _seed_transcripts_dir(repo, ticker, [(1, 2026, _aggregator_qa("Q1 2026", "B: question."))])
    _seed_transcripts_db(repo, ticker, [(1, 2026, True)])

    call_count = {"n": 0}

    def fake_extractor(_t: str, _x: list[dict[str, Any]]) -> str:
        call_count["n"] += 1
        return _mock_themes_response(
            prepared=[],
            qa=[
                {"theme_name": "Question shape", "mentions_per_quarter": {"Q1 2026": 1}, "evidence": []}
            ],
        )

    import llm_client

    monkeypatch.setattr(llm_client, "extract_qa_vs_prepared_themes", fake_extractor)

    section1 = build(ticker, repo, enable_llm=True)
    section2 = build(ticker, repo, enable_llm=True)
    assert call_count["n"] == 1, "second build should hit the on-disk cache"
    assert section1.qa_themes[0].theme_name == section2.qa_themes[0].theme_name
    # Cache file is the source-of-truth on disk
    assert (repo / "data" / "earnings_themes" / "CACHE.json").exists()


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------


def _sample_section_with_themes() -> EarningsSection:
    return EarningsSection(
        status=SectionStatus.OK,
        prepared_remarks_themes=[
            ThemeRollup(
                theme_name="CapEx trajectory",
                last_4q_count=4,
                mentions_per_quarter={"Q4 2025": 2, "Q1 2026": 2},
                evidence=[
                    QuoteSnippet(
                        period="Q1 2026",
                        speaker="Anat Ashkenazi",
                        text="CapEx will increase significantly going into 2027.",
                    )
                ],
            )
        ],
        qa_themes=[
            ThemeRollup(
                theme_name="AI compute capacity",
                last_4q_count=5,
                mentions_per_quarter={"Q1 2026": 3, "Q4 2025": 2},
                evidence=[
                    QuoteSnippet(
                        period="Q1 2026",
                        speaker="Brian Nowak (Morgan Stanley)",
                        text="How are you thinking about compute allocation?",
                    )
                ],
            )
        ],
    )


def test_md_renders_both_theme_blocks() -> None:
    out = StringIO()
    md_earnings(out, _sample_section_with_themes())
    s = out.getvalue()
    assert "Cross-quarter themes" in s
    assert "Prepared remarks themes" in s
    assert "Q&A themes" in s
    assert "CapEx trajectory" in s
    assert "AI compute capacity" in s
    # Sparkline shows per-quarter mention counts
    assert "Q4 2025:2" in s
    assert "Q1 2026:2" in s
    # Quote evidence is rendered with the speaker attribution
    assert "Anat Ashkenazi" in s
    assert "CapEx will increase significantly going into 2027" in s


def test_md_renders_fallback_note_when_qa_missing() -> None:
    section = EarningsSection(
        status=SectionStatus.OK,
        prepared_remarks_themes=[
            ThemeRollup(
                theme_name="Top-line growth framing",
                last_4q_count=2,
                mentions_per_quarter={"Q4 2025": 1, "Q1 2026": 1},
                evidence=[],
            )
        ],
        qa_themes=[],
        themes_note="No Q&A sections available in transcripts.",
    )
    out = StringIO()
    md_earnings(out, section)
    s = out.getvalue()
    assert "Prepared remarks themes" in s
    assert "No Q&A sections available" in s
    # The Q&A themes header should NOT render when qa_themes is empty
    assert "Q&A themes" not in s


def test_md_skips_themes_block_when_offline() -> None:
    """Default-empty section (built without --enable-llm) doesn't render the
    themes block at all, so non-LLM builds stay clean."""
    section = EarningsSection(status=SectionStatus.OK)
    out = StringIO()
    md_earnings(out, section)
    s = out.getvalue()
    assert "Cross-quarter themes" not in s


def test_html_renders_both_theme_blocks() -> None:
    out = StringIO()
    html_earnings(out, _sample_section_with_themes())
    s = out.getvalue()
    assert "Cross-quarter themes" in s
    assert "Prepared remarks themes" in s
    assert "Q&amp;A themes" in s  # & is escaped in HTML
    assert "CapEx trajectory" in s
    assert "AI compute capacity" in s
    assert "theme-rollup" in s
    assert "Anat Ashkenazi" in s


def test_html_renders_fallback_note_when_qa_missing() -> None:
    section = EarningsSection(
        status=SectionStatus.OK,
        prepared_remarks_themes=[
            ThemeRollup(theme_name="Some theme", last_4q_count=1, mentions_per_quarter={"Q1 2026": 1}, evidence=[])
        ],
        qa_themes=[],
        themes_note="No Q&A sections available in transcripts.",
    )
    out = StringIO()
    html_earnings(out, section)
    s = out.getvalue()
    assert "Prepared remarks themes" in s
    assert "No Q&amp;A sections available" in s
    # Q&A header should not appear when qa_themes is empty
    assert "<h4>Q&amp;A themes</h4>" not in s


def test_html_skips_themes_block_when_offline() -> None:
    out = StringIO()
    html_earnings(out, EarningsSection(status=SectionStatus.OK))
    s = out.getvalue()
    assert "Cross-quarter themes" not in s


# ---------------------------------------------------------------------------
# Workspace renderer panel
# ---------------------------------------------------------------------------


def test_workspace_renders_themes_panel() -> None:
    from report.models import FinancialsSection
    from report.renderers.workspace_html import _earnings_tab

    out = StringIO()
    _earnings_tab(
        out,
        _sample_section_with_themes(),
        FinancialsSection(status=SectionStatus.OK),
        None,
    )
    s = out.getvalue()
    assert "Cross-quarter themes" in s
    assert "CapEx trajectory" in s
    assert "AI compute capacity" in s
    assert "theme-bucket" in s


def test_workspace_skips_themes_panel_when_empty() -> None:
    from report.models import FinancialsSection
    from report.renderers.workspace_html import _earnings_tab

    out = StringIO()
    _earnings_tab(
        out,
        EarningsSection(status=SectionStatus.OK),
        FinancialsSection(status=SectionStatus.OK),
        None,
    )
    s = out.getvalue()
    assert "Cross-quarter themes" not in s


# ---------------------------------------------------------------------------
# Reference: defensive parsing of the LLM payload guarantees the builder
# never propagates Pydantic ValidationErrors out of the section.
# ---------------------------------------------------------------------------


def test_parse_themes_response_drops_themes_with_blank_name() -> None:
    raw = json.dumps(
        {
            "prepared_themes": [
                {"theme_name": "", "mentions_per_quarter": {}, "evidence": []},
                {"theme_name": "valid", "mentions_per_quarter": {"Q1 2026": 1}, "evidence": []},
            ],
            "qa_themes": [],
        }
    )
    prepared, _ = _parse_themes_response(raw)
    assert len(prepared) == 1
    assert prepared[0].theme_name == "valid"


def test_parse_themes_response_evidence_without_text_dropped() -> None:
    raw = json.dumps(
        {
            "prepared_themes": [
                {
                    "theme_name": "T",
                    "mentions_per_quarter": {"Q1 2026": 1},
                    "evidence": [
                        {"period": "Q1 2026", "speaker": "x"},  # no text → dropped
                        {"period": "Q1 2026", "text": "valid quote"},
                    ],
                }
            ],
            "qa_themes": [],
        }
    )
    prepared, _ = _parse_themes_response(raw)
    assert len(prepared[0].evidence) == 1
    assert prepared[0].evidence[0].text == "valid quote"
    # Reference earnings_section to mark the import as used (it surfaces the
    # cache path in failure mode; explicit reference avoids ruff F401 churn
    # if a refactor drops a direct call).
    assert hasattr(earnings_section, "_themes_cache_path")
