"""Shared style master for operations and quality diagnostic panels.

The panel modules own markup and behavior; this module owns their scoped
presentation so conformance scanning has one source of truth.
"""

TRIAGE_STYLE = """<style>
.tri-sub{color:var(--muted);font-size:var(--fs-caption);margin:0 0 var(--sp-3);line-height:1.55;max-width:70ch}.tri-anchor{font-family:var(--mono);font-size:var(--fs-caption);color:var(--muted);white-space:nowrap}.tri-when{color:var(--muted);font-variant-numeric:tabular-nums;white-space:nowrap}.tri-text{background:none;border:none;padding:0;text-align:left;cursor:pointer;font:inherit;color:var(--fg)}.tri-text:hover{color:var(--accent);text-decoration:underline}.tri-acts{display:flex;gap:var(--sp-2);align-items:center;flex-wrap:wrap}.tri-route{font-size:var(--fs-caption);padding-top:3px;padding-bottom:3px}.tri-empty{color:var(--muted);padding:var(--sp-4) 0}.tri-h{font-size:var(--fs-title);font-weight:600;color:var(--fg);margin:var(--sp-4) 0 var(--sp-1);display:flex;align-items:baseline;gap:var(--sp-2)}.tri-resolve-ta{width:100%;min-height:48px;resize:vertical;font-family:var(--sans);font-size:var(--fs-body);margin-bottom:var(--sp-2)}#triage-drawer{top:var(--sp-3);right:var(--sp-3);width:min(420px,92vw);max-height:calc(100vh - var(--sp-3) * 2);max-height:calc(100dvh - var(--sp-3) * 2);padding:var(--sp-4);overflow:auto;gap:var(--sp-3)}#triage-drawer:not([hidden]){display:flex;flex-direction:column}.tri-d-bar{display:flex;align-items:baseline;gap:var(--sp-2)}.tri-d-bar h3{font-size:var(--fs-title);font-weight:600;margin:0;margin-right:auto}.tri-d-close{background:none;border:none;cursor:pointer;color:var(--muted);font-size:var(--fs-display);line-height:1;padding:0 var(--sp-1)}.tri-d-close:hover{color:var(--fg)}.tri-d-meta{color:var(--muted);font-size:var(--fs-caption);font-family:var(--mono);line-height:1.6}.tri-d-sel{color:var(--fg-soft);border-left:2px solid var(--border);padding-left:var(--sp-3)}.tri-d-body{font-size:var(--fs-body);line-height:1.6;color:var(--fg);white-space:pre-wrap}#tri-d-acts{border-top:1px solid var(--hairline);padding-top:var(--sp-3)}
</style>"""

CALIBRATION_SCORECARD_STYLE = """<style>
.cs-gate{font-size:var(--fs-caption);margin:2px 0 8px}.cs-gate-ok{color:var(--ok)}.cs-gate-bad{color:var(--bad)}.cs-biases{display:flex;flex-direction:column;gap:10px}.cs-bias{border-left:3px solid var(--border);padding:2px 0 2px 12px}.cs-bias-name{font-size:var(--fs-body);font-weight:600;margin:0 0 2px;text-transform:none;letter-spacing:0}.cs-bias-pattern{font-size:var(--fs-body);margin:0 0 4px}.cs-evidence{margin:0 0 4px;padding-left:18px;font-size:var(--fs-caption);color:var(--muted)}.cs-tell,.cs-exp-test{font-size:var(--fs-caption);margin:2px 0}.cs-tell-k{font-family:var(--sans);color:var(--muted);text-transform:uppercase;font-size:var(--fs-caption);letter-spacing:.04em;margin-right:6px}.cs-experiment{margin-top:12px}.cs-exp-hyp{font-size:var(--fs-body);font-weight:600;margin:0 0 2px}.cs-exp-why{font-size:var(--fs-caption);color:var(--muted);margin:0 0 4px}.cs-note{font-size:var(--fs-caption);margin:6px 0 0}.cs-caption{font-size:var(--fs-caption);margin:2px 0 0}
</style>"""

EVALS_STYLE = """<style>
.ev-runbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;background:var(--surface);border:1px solid var(--border);border-radius:var(--radius);padding:10px 14px;margin-bottom:18px;font-size:var(--fs-body)}.ev-capture-group{width:100%}.ev-capture-buttons{display:flex;gap:8px;flex-wrap:wrap;padding-top:8px}.ev-note{font-size:var(--fs-caption)}.ev-log{width:100%;margin:8px 0 0;padding:8px 10px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-family:var(--mono);font-size:var(--fs-caption);max-height:180px;overflow-y:auto;white-space:pre-wrap}.ev-drawer-row>td{padding:0 0 10px 12px;border:none}.ev-vchip{margin-right:8px;cursor:help}.ev-bad{color:var(--bad);font-weight:600}.ev-warn{color:var(--warn);font-weight:600}.ev-purpose{font-weight:600}.ev-loc{font-family:var(--mono)}
</style>"""

DISCOVERY_STYLE = """<style>
.dq-count{color:var(--muted);font-size:var(--fs-caption)}#dq-list .dq-count{display:none}#dq-list [data-cand-id]{cursor:pointer}#dq-list tr[data-cand-id]:hover>td{background:var(--paper)}.dq-why{color:var(--fg-soft)}.dq-why-line{display:flex;align-items:baseline;gap:var(--sp-2)}.dq-peek{background:none;border:none;color:var(--muted);cursor:pointer;font-size:var(--fs-caption);padding:0}.dq-peek:hover{color:var(--accent)}.dq-detail[hidden]{display:none}.dq-detail td{padding-top:0}.dq-evtable{width:100%;border-collapse:collapse;font-size:var(--fs-caption);font-variant-numeric:tabular-nums;color:var(--muted)}.dq-evtable td{padding:2px var(--sp-2);border:none}.dq-evtable .dq-src{font-family:var(--mono);color:var(--fg-soft)}.dq-acts{display:flex;gap:var(--sp-1);flex-wrap:wrap;align-items:center}.dq-srcwt{width:4.5rem}.dq-cards{display:flex;flex-direction:column;gap:var(--sp-3)}.dq-card-head{display:flex;align-items:center;gap:var(--sp-2);flex-wrap:wrap}.dq-card-head .dq-peek{margin-left:auto}.dq-card-row{display:flex;gap:var(--sp-2);align-items:baseline;margin-top:var(--sp-2);font-size:var(--fs-body)}.dq-card-label{color:var(--muted);font-size:var(--fs-caption);text-transform:uppercase;letter-spacing:.05em;min-width:6.5rem;flex-shrink:0}.dq-card .dq-detail{margin-top:var(--sp-2)}.dq-more{margin-top:var(--sp-3)}.dq-more>summary{cursor:pointer;color:var(--muted);font-size:var(--fs-caption)}.dq-sources{margin-top:var(--sp-3)}.dq-saved{color:var(--ok);font-size:var(--fs-caption);margin-left:var(--sp-2);opacity:0;transition:opacity var(--transition)}.dq-saved.is-on{opacity:1}.dq-log{margin-top:var(--sp-3);max-height:280px;overflow-y:auto;font-family:var(--mono);font-size:var(--fs-caption);color:var(--fg-soft);white-space:pre-wrap;display:none}.dq-log.is-on{display:block}.dq-hint{color:var(--muted);font-size:var(--fs-caption);margin-top:var(--sp-3)}.dq-empty{color:var(--muted);padding:var(--sp-4) 0}.dq-dismiss-label{display:block;color:var(--muted);font-size:var(--fs-caption);margin:var(--sp-2) 0 var(--sp-1)}.dq-dismiss-label:first-child{margin-top:0}.dq-dismiss-ta,.dq-dismiss-revisit{width:100%;box-sizing:border-box;font-family:var(--sans);font-size:var(--fs-body)}.dq-dismiss-ta{min-height:48px;resize:vertical}.dq-dismiss-row{display:flex;gap:var(--sp-2);margin-top:var(--sp-2)}
</style>"""

MOBILE_INBOX_STYLE = """<style>
:root{color-scheme:light}body{margin:0;padding:var(--sp-3);background:var(--paper);font-family:var(--sans);max-width:560px;margin-left:auto;margin-right:auto}.mi-h1{font-size:var(--fs-title);font-weight:600;color:var(--fg);margin:0 0 var(--sp-3)}.mi-sec{margin-bottom:var(--sp-5)}.mi-sec-h{font-size:var(--fs-caption);font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin:0 0 var(--sp-2)}.mi-card{border:1px solid var(--border);border-radius:var(--radius);background:var(--surface);padding:var(--sp-3);margin-bottom:var(--sp-2)}.mi-card.mi-deferred{opacity:.4}.mi-card-head{display:flex;align-items:baseline;gap:var(--sp-2);flex-wrap:wrap;margin-bottom:var(--sp-1)}.mi-body{color:var(--fg-soft);font-size:var(--fs-body);line-height:1.5;margin:var(--sp-1) 0}.cr-receipt{color:var(--muted);font-size:var(--fs-caption);margin:var(--sp-1) 0}.mi-actions{display:flex;gap:var(--sp-2);flex-wrap:wrap;margin-top:var(--sp-2)}.mi-correct-form{display:grid;grid-template-columns:1fr 1fr;gap:var(--sp-2);margin-top:var(--sp-2)}.mi-correct-form label{display:grid;gap:var(--sp-1);color:var(--muted);font-size:var(--fs-caption)}.mi-correct-form .mi-wide{grid-column:1 / -1}.mi-empty,.mi-failed,.mi-not-generated{color:var(--muted);font-size:var(--fs-body);padding:var(--sp-3) 0}.mi-failed{color:var(--bad)}.mi-recover{display:block;margin-top:var(--sp-1);font-size:var(--fs-caption)}
</style>"""

CRON_HEALTH_STYLE = """<style>
.ch-dir{font-weight:600;white-space:nowrap}.ch-dots{white-space:nowrap}.ch-dot{margin:0 1px}.ch-dot-miss{color:var(--border)}.ch-status-ok{color:var(--ok);font-weight:600}.ch-status-fail{color:var(--bad);font-weight:600}.ch-status-miss{color:var(--muted)}.ch-note{margin-top:14px;padding:10px 13px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-size:var(--fs-body);line-height:1.55}.ch-note code,.ch-alarm code{background:var(--surface);padding:1px 5px;border-radius:var(--radius)}.ch-alarm{margin-bottom:var(--sp-3);line-height:1.55}.ch-alarm strong{display:block;margin-bottom:var(--sp-1)}
</style>"""

MODEL_EVAL_STYLE = """<style>
.me-alarm{display:flex;align-items:center;gap:var(--sp-2);margin-bottom:var(--sp-2)}.me-alarm-chips{display:flex;flex-wrap:wrap;gap:var(--sp-2)}.me-alarm-chip{gap:var(--sp-2)}.me-alarm-cost{font-family:var(--mono)}.me-rollup{font-size:var(--fs-body);margin:0 0 var(--sp-3)}.me-savings{font-family:var(--mono);color:var(--ok);font-weight:600}.me-purpose{font-weight:600}.me-vs{font-weight:400}.me-loc{font-family:var(--mono)}.me-total{font-weight:600}.me-cost-total>td{border-top:2px solid var(--border)}.me-verdicts{width:100%;border-collapse:collapse;font-size:var(--fs-body)}.me-verdicts td{padding:var(--sp-2) var(--sp-3);border-bottom:1px solid var(--border);text-align:left;vertical-align:top}.me-cand{display:inline-flex;align-items:center;gap:var(--sp-2);margin:0 var(--sp-3) var(--sp-1) 0}.me-infra,.me-frame-chip{cursor:help}
</style>"""

GENERIC_STYLES = {
    "validation": "<style>.vi-raw{font-family:var(--mono);font-size:var(--fs-caption);word-break:break-all}.vi-note{margin-top:14px;line-height:1.55}.vi-note code{background:var(--surface);padding:1px 5px;border-radius:var(--radius)}</style>",
    "restatements": "<style>.rs-was{color:var(--muted);text-decoration:line-through}.rs-now{font-weight:600}.rs-up{color:var(--ok)}.rs-down{color:var(--bad)}.rs-note{margin-top:14px;padding:10px 13px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-size:var(--fs-body);line-height:1.55}.rs-note code{background:var(--surface);padding:1px 5px;border-radius:var(--radius)}.rs-doc{font-size:var(--fs-caption);font-family:var(--mono)}</style>",
    "credibility": "<style>.cred-note{margin-top:14px}.cred-over{color:var(--bad)}.cred-under{color:var(--ok)}.cred-spark{font-weight:600}.cred-thin{color:var(--muted);font-size:var(--fs-caption)}</style>",
    "dcf": "<style>.dcv-ok{color:var(--ok);font-weight:600}.dcv-warn{color:var(--warn);font-weight:600}.dcv-bad{color:var(--bad);font-weight:600}.dcv-muted{color:var(--muted)}.dcv-note{margin-top:14px;padding:10px 13px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-size:var(--fs-body);line-height:1.55}.dcv-note code{background:var(--surface);padding:1px 5px;border-radius:var(--radius)}</style>",
    "section_coverage": "<style>.sc-matrix.p-table th,.sc-matrix.p-table td{font-size:var(--fs-caption)}.sc-matrix.p-table th{letter-spacing:.05em}.sc-matrix.p-table td{padding:5px 7px;text-align:center;white-space:nowrap}.sc-list{color:var(--muted);font-size:var(--fs-caption)}.sc-filled{color:var(--ok)}.sc-empty{color:var(--muted)}.sc-na{color:var(--border-2)}.sc-noreport{color:var(--warn);font-size:var(--fs-caption)}.sc-gaps{font-variant-numeric:tabular-nums;color:var(--muted)}.sc-note{margin-top:14px;padding:10px 13px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-size:var(--fs-body);line-height:1.55;color:var(--muted)}</style>",
    "ir": "<style>.ir-cov-table td.tk{font-weight:600;font-family:var(--mono)}.ir-reason{font-size:var(--fs-caption);color:var(--muted);margin-top:3px}.ir-note{margin-top:14px;padding:10px 13px;background:var(--paper);border:1px solid var(--border);border-radius:var(--radius);font-size:var(--fs-body);line-height:1.55}.ir-note code{background:var(--surface);padding:1px 5px;border-radius:var(--radius)}</style>",
    "fact_overrides": "<style>.fov-tick{font-weight:600;white-space:nowrap}.fov-act-replace{color:var(--ok);font-weight:600}.fov-act-drop{color:var(--bad);font-weight:600}.fov-act-qualify{color:var(--warn);font-weight:600}.fov-muted{color:var(--muted)}.fov-src{font-family:var(--mono);font-size:var(--fs-caption);color:var(--muted);white-space:nowrap}</style>",
}

OPERATIONS_STYLE = """<style>
.operations-panel{gap:var(--sp-4)}.operations-related,.operations-tabs,.operations-filter,.ops-attention-actions{display:flex;gap:var(--sp-2);flex-wrap:wrap}.operations-tabs [role=tab],.operations-related .k-btn,.operations-filter .k-chip,.ops-task-card summary,.operations-tab,.ops-attention-actions .k-btn{min-block-size:var(--touch-target-size)}.operations-filter .k-chip:focus-visible{outline:var(--bw-thin) solid var(--accent);outline-offset:var(--sp-1)}.ops-summary-grid,.ops-runtime-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(var(--grid-card-sm),1fr));gap:var(--sp-3)}.ops-job-tools{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:end;gap:var(--sp-3)}.ops-job-tools>.k-label{grid-column:1 / -1}.ops-job-tools input{min-block-size:var(--touch-target-size)}.ops-task-list,.ops-task-card,.ops-task-card ol,.ops-attention-list,.ops-attention-card{display:grid;gap:var(--sp-3);min-inline-size:0}.ops-task-facts,.ops-attention-facts,.ops-attention-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--sp-3)}.ops-attention-control{display:grid;gap:var(--sp-1);min-inline-size:0}.ops-attention-control input,.ops-attention-control select{min-block-size:var(--touch-target-size);min-inline-size:0}.ops-attention-card .k-card-meta,.ops-attention-ref{overflow-wrap:anywhere}.ops-readme-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--sp-3)}.ops-governance-actions{display:flex;align-items:center;flex-wrap:wrap;gap:var(--sp-2)}.ops-governance-actions .k-btn{min-block-size:var(--touch-target-size)}.operations-panel [role=tabpanel]{display:grid;gap:var(--sp-3);min-inline-size:0}.operations-panel [role=tabpanel][hidden]{display:none}.policy-grid,.policy-scroll,.policy-toolbar,.policy-chips,.policy-stack,.policy-dl{display:grid;gap:var(--sp-3)}.policy-grid,.policy-dl{grid-template-columns:repeat(auto-fit,minmax(var(--grid-card-sm),1fr))}.policy-scroll{overflow-x:auto}.policy-toolbar{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap}.policy-chips{display:flex;flex-wrap:wrap}.policy-chips-top{margin-top:var(--sp-3)}.policy-stack{grid-template-columns:1fr}.policy-dl{margin:var(--sp-3) 0 0}.policy-events{margin-top:var(--sp-3)}.operations-tab{min-block-size:var(--touch-target-size)}
@media (max-width:48rem){.ops-job-tools,.ops-task-facts,.ops-attention-facts,.ops-attention-controls,.ops-readme-facts{grid-template-columns:1fr}.operations-related .k-btn,.operations-filter .k-chip,.ops-attention-actions .k-btn{flex:1 1 auto}}
</style>"""

DCF_GLOBALS_STYLE = """<style>
.dcfg-row { margin-bottom:var(--sp-4); }
.dcfg-controls { display:flex; gap:var(--sp-2); align-items:center; flex-wrap:wrap; }
.dcfg-label { min-inline-size:var(--grid-card-sm); }
.dcfg-input { inline-size:calc(var(--grid-card-sm) / 3); padding:var(--sp-1) var(--sp-2); }
.dcfg-pct { min-inline-size:calc(var(--grid-card-sm) / 4); }
.dcfg-msg,.dcfg-rebuild-msg { font-size:var(--fs-caption); }
.dcfg-reach { font-size:var(--fs-caption); margin-top:var(--sp-3); }
.dcfg-rebuild-controls { margin-top:var(--sp-2); }
.dcfg-rebuild-log { max-block-size:var(--grid-card-sm); overflow:auto; white-space:pre-wrap;
  font-family:var(--mono); font-size:var(--fs-body); margin-top:var(--sp-2); }
.dcfg-rebuild-log[hidden] { display:none; }
</style>"""

IR_APPROVAL_STYLE = """<style>
.ir-approval-card { min-width:0; }
.ir-approval-value { min-width:0; overflow-wrap:anywhere; }
</style>"""

VALIDATION_STYLE = GENERIC_STYLES["validation"]
RESTATEMENTS_STYLE = GENERIC_STYLES["restatements"]
CREDIBILITY_STYLE = GENERIC_STYLES["credibility"]
DCF_STYLE = GENERIC_STYLES["dcf"]
SECTION_COVERAGE_STYLE = GENERIC_STYLES["section_coverage"]
IR_STYLE = GENERIC_STYLES["ir"]
FACT_OVERRIDES_STYLE = GENERIC_STYLES["fact_overrides"]
