"""The Streamlit sandbox's control kit: parity by construction, not by copy.

The settled sandbox scope is token parity + control-kit reuse. This module
is the single import point that makes both true mechanically:

- :func:`theme_css` composes ``palette_css("dark")`` + ``controls_css("dark")``
  — the SAME two layers every Flask page composes, in the same order (the
  controls layer "rides immediately after palette_css" per the composition
  contract in ``src/ui/controls.py``). No sandbox-authored CSS exists
  anywhere; the drift test pins that this function emits exactly those two
  layers and nothing else.
- The control helpers are re-exported from ``src/ui/controls.py`` — the same
  functions the Flask cockpit calls, never a fork. ``__all__`` is the
  sanctioned surface for the deep-dive app; extend it only when the app
  needs another registered control.

No streamlit import here — the kit emits strings; the app
(``analytics_deep_dive.py``) owns ``st.markdown``. That keeps the kit, and
its drift test (``tests/test_explore_sandbox_kit.py``), runnable in every
checkout: the sandbox is an optional-dependency surface.

The committed mirrors under ``theme/`` (tokens.css, controls.css) and
``.streamlit/config.toml`` are generated by ``scripts/gen_streamlit_theme.py``
and drift-checked by the design-sync gate; the kit composes the functions
directly so it can never serve a stale artifact.
"""

from __future__ import annotations

import sys
from pathlib import Path

SANDBOX_DIR = Path(__file__).resolve().parent
_REPO_SRC = SANDBOX_DIR.parent / "src"
if str(_REPO_SRC) not in sys.path:
    sys.path.insert(0, str(_REPO_SRC))

from ui.controls import (  # noqa: E402
    chip_tone_class,
    controls_css,
    fact_anchor_attrs,
    icon_svg,
    k_empty,
    panel_section_title,
    panel_toolbar,
    pill_tone_class,
    prov_drawer,
    prov_row,
    prov_severity_tone,
    thesis_status_tone,
    ticker_label,
)
from ui.tokens import palette_css  # noqa: E402

__all__ = [
    "chip_tone_class",
    "fact_anchor_attrs",
    "icon_svg",
    "k_empty",
    "panel_section_title",
    "panel_toolbar",
    "pill_tone_class",
    "prov_drawer",
    "prov_row",
    "prov_severity_tone",
    "theme_css",
    "thesis_status_tone",
    "ticker_label",
]


def theme_css() -> str:
    """The sandbox's full injected style layer: the dark token layer then the
    control kit layer, verbatim from the authorities, nothing else."""
    return palette_css("dark") + "\n" + controls_css("dark")
