"""Resolve KPI definition source subjects through admitted as-known bindings.

Only the three identity predicates change. Raw documents and all other evidence,
clock, lifecycle and head predicates retain their predecessor bytes.
New binding clock comparisons preserve six-digit fractions and UTC/minute offsets.
Unsupported suffixes fail closed, including any unreadable newer binding.
"""

from __future__ import annotations

import hashlib

from sqlalchemy import text

from alembic import op

revision = "0055_kpi_definition_subject_bindings"
down_revision = "0054_filing_xbrl_unit_protocol"
branch_labels = None
depends_on = None

# Frozen predecessor and successor SQLite trigger SQL hashes.
_REWRITES = (
    (
        "trg_kpi_definition_revisions_source",
        "ca618effac64bb91789e1896f5589e2bf137e43d368416080653823a58607d9f",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        "305f6c6985fe642f9973ef4bbea7affb954977230d22596e30c54f51d6154b86",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        (
            (
                "entity.issuer_id=document.issuer_id",
                "(entity.issuer_id=document.issuer_id OR EXISTS (\n"
                "                    SELECT 1 FROM recorded_subject_binding_revisions subject\n"
                "                    WHERE subject.recorded_issuer_id=document.issuer_id\n"
                "                      AND subject.outcome='selected'\n"
                "                      AND subject.issuer_id=entity.issuer_id\n"
                "                      AND subject.reporting_entity_id=entity.reporting_entity_id\n"
                "                      AND subject.material_dissent=0\n"
                "                      AND (CASE WHEN (substr(subject.knowledge_at,20)=(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) "
                "WHEN substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND "
                "(CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.knowledge_at,1,19)||(CASE WHEN subject.knowledge_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)||'000000',1,6) AS "
                "INTEGER)) END)<=(CASE WHEN (substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR (substr(NEW.knowledge_at,20,1)='.' "
                "AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND (CASE WHEN (substr(subject.recorded_at,20)=(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) "
                "WHEN substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.recorded_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(subject.recorded_at,20,1)='.' "
                "THEN substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.recorded_at,1,19)||(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.recorded_at,20)=(CASE WHEN NEW.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN "
                "substr(NEW.recorded_at,-6) WHEN substr(NEW.recorded_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(NEW.recorded_at,20,1)='.' AND length((CASE WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.recorded_at,1,19)||(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.recorded_at,-6) WHEN "
                "substr(NEW.recorded_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND NOT EXISTS (\n"
                "                          SELECT 1 FROM recorded_subject_binding_revisions newer\n"
                "                          WHERE newer.recorded_issuer_id=subject.recorded_issuer_id\n"
                "                            AND newer.revision>subject.revision\n"
                "                            AND ((CASE WHEN (substr(newer.knowledge_at,20)=(CASE WHEN "
                "newer.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END) IS NULL OR (CASE WHEN "
                "(substr(newer.knowledge_at,20)=(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' "
                "THEN substr(NEW.knowledge_at,-6) WHEN substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) "
                "OR (substr(NEW.knowledge_at,20,1)='.' AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' "
                "THEN substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)))))",
            ),
            ("security.issuer_id=document.issuer_id", "security.issuer_id=entity.issuer_id"),
        ),
    ),
    (
        "trg_kpi_definition_comparability_source",
        "9c7fd389ab3361027d23f49a29a0115b2f3a50908300f88a6f804be2e91c8cef",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        "4ba1a63aa838ae4f64c05b919da75eff668ad42dfb57f0a3161127ed3738a28b",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        (
            (
                "document.issuer_id=predecessor_entity.issuer_id",
                "(predecessor_entity.issuer_id=document.issuer_id OR EXISTS (\n"
                "                    SELECT 1 FROM recorded_subject_binding_revisions subject\n"
                "                    WHERE subject.recorded_issuer_id=document.issuer_id\n"
                "                      AND subject.outcome='selected'\n"
                "                      AND subject.issuer_id=predecessor_entity.issuer_id\n"
                "                      AND subject.reporting_entity_id=successor_entity.reporting_entity_id\n"
                "                      AND subject.material_dissent=0\n"
                "                      AND (CASE WHEN (substr(subject.knowledge_at,20)=(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) "
                "WHEN substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND "
                "(CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.knowledge_at,1,19)||(CASE WHEN subject.knowledge_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)||'000000',1,6) AS "
                "INTEGER)) END)<=(CASE WHEN (substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR (substr(NEW.knowledge_at,20,1)='.' "
                "AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND (CASE WHEN (substr(subject.recorded_at,20)=(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) "
                "WHEN substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.recorded_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(subject.recorded_at,20,1)='.' "
                "THEN substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.recorded_at,1,19)||(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.recorded_at,20)=(CASE WHEN NEW.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN "
                "substr(NEW.recorded_at,-6) WHEN substr(NEW.recorded_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(NEW.recorded_at,20,1)='.' AND length((CASE WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.recorded_at,1,19)||(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.recorded_at,-6) WHEN "
                "substr(NEW.recorded_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.recorded_at,20,1)='.' THEN "
                "substr(NEW.recorded_at,21,length(NEW.recorded_at)-20-(CASE WHEN NEW.recorded_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND NOT EXISTS (\n"
                "                          SELECT 1 FROM recorded_subject_binding_revisions newer\n"
                "                          WHERE newer.recorded_issuer_id=subject.recorded_issuer_id\n"
                "                            AND newer.revision>subject.revision\n"
                "                            AND ((CASE WHEN (substr(newer.knowledge_at,20)=(CASE WHEN "
                "newer.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END) IS NULL OR (CASE WHEN "
                "(substr(newer.knowledge_at,20)=(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' "
                "THEN substr(NEW.knowledge_at,-6) WHEN substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) "
                "OR (substr(NEW.knowledge_at,20,1)='.' AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' "
                "THEN substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)))))",
            ),
        ),
    ),
    (
        "trg_kpi_fact_semantic_definition_exact",
        "703a3b1ac5f96c7e9b815bc9cac7e56dd3884df87af43f7130dd799cfc8ddd0e",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        "d2a5abb63f2ad13fb34e8be656f73f95484e42f1123654c217b423af30c039a2",  # pragma: allowlist secret -- deterministic SQLite trigger digest, not a credential
        (
            (
                "entity.issuer_id=COALESCE(\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM v_legacy_document_evidence_bindings_current binding\n"
                "                     JOIN evidence_document_versions document\n"
                "                       ON document.document_version_id=binding.document_version_id\n"
                "                     WHERE binding.legacy_document_id=fact.source_doc_id LIMIT 1),\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM evidence_document_versions document\n"
                "                     WHERE document.legacy_document_id=fact.source_doc_id\n"
                "                     ORDER BY document.version_sequence DESC LIMIT 1))",
                "(entity.issuer_id=COALESCE(\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM v_legacy_document_evidence_bindings_current binding\n"
                "                     JOIN evidence_document_versions document\n"
                "                       ON document.document_version_id=binding.document_version_id\n"
                "                     WHERE binding.legacy_document_id=fact.source_doc_id LIMIT 1),\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM evidence_document_versions document\n"
                "                     WHERE document.legacy_document_id=fact.source_doc_id\n"
                "                     ORDER BY document.version_sequence DESC LIMIT 1)) OR EXISTS (\n"
                "                    SELECT 1 FROM recorded_subject_binding_revisions subject\n"
                "                    WHERE subject.recorded_issuer_id=COALESCE(\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM v_legacy_document_evidence_bindings_current binding\n"
                "                     JOIN evidence_document_versions document\n"
                "                       ON document.document_version_id=binding.document_version_id\n"
                "                     WHERE binding.legacy_document_id=fact.source_doc_id LIMIT 1),\n"
                "                    (SELECT document.issuer_id\n"
                "                     FROM evidence_document_versions document\n"
                "                     WHERE document.legacy_document_id=fact.source_doc_id\n"
                "                     ORDER BY document.version_sequence DESC LIMIT 1))\n"
                "                      AND subject.outcome='selected'\n"
                "                      AND subject.issuer_id=entity.issuer_id\n"
                "                      AND subject.reporting_entity_id=entity.reporting_entity_id\n"
                "                      AND subject.material_dissent=0\n"
                "                      AND (CASE WHEN (substr(subject.knowledge_at,20)=(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) "
                "WHEN substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND "
                "(CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.knowledge_at,1,19)||(CASE WHEN subject.knowledge_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.knowledge_at,-6) WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.knowledge_at,20,1)='.' THEN "
                "substr(subject.knowledge_at,21,length(subject.knowledge_at)-20-(CASE WHEN "
                "subject.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END)||'000000',1,6) AS "
                "INTEGER)) END)<=(CASE WHEN (substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR (substr(NEW.knowledge_at,20,1)='.' "
                "AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND (CASE WHEN (substr(subject.recorded_at,20)=(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) "
                "WHEN substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(subject.recorded_at,20,1)='.' AND length((CASE WHEN "
                "substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(subject.recorded_at,20,1)='.' "
                "THEN substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN "
                "subject.recorded_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 1 ELSE 0 END)) ELSE '' END) NOT GLOB '*[^0-9]*')) "
                "THEN (CAST(strftime('%s',substr(subject.recorded_at,1,19)||(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(subject.recorded_at,-6) WHEN "
                "substr(subject.recorded_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(subject.recorded_at,20,1)='.' THEN "
                "substr(subject.recorded_at,21,length(subject.recorded_at)-20-(CASE WHEN subject.recorded_at "
                "GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(subject.recorded_at,-1)='Z' THEN 1 ELSE "
                "0 END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.created_at,20)=(CASE WHEN NEW.created_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN "
                "substr(NEW.created_at,-6) WHEN substr(NEW.created_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(NEW.created_at,20,1)='.' AND length((CASE WHEN substr(NEW.created_at,20,1)='.' THEN "
                "substr(NEW.created_at,21,length(NEW.created_at)-20-(CASE WHEN NEW.created_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.created_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.created_at,20,1)='.' THEN "
                "substr(NEW.created_at,21,length(NEW.created_at)-20-(CASE WHEN NEW.created_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.created_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.created_at,1,19)||(CASE WHEN NEW.created_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.created_at,-6) WHEN "
                "substr(NEW.created_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.created_at,20,1)='.' THEN "
                "substr(NEW.created_at,21,length(NEW.created_at)-20-(CASE WHEN NEW.created_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.created_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)\n"
                "                      AND NOT EXISTS (\n"
                "                          SELECT 1 FROM recorded_subject_binding_revisions newer\n"
                "                          WHERE newer.recorded_issuer_id=subject.recorded_issuer_id\n"
                "                            AND newer.revision>subject.revision\n"
                "                            AND ((CASE WHEN (substr(newer.knowledge_at,20)=(CASE WHEN "
                "newer.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END) IS NULL OR (CASE WHEN "
                "(substr(newer.knowledge_at,20)=(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) OR "
                "(substr(newer.knowledge_at,20,1)='.' AND length((CASE WHEN "
                "substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(newer.knowledge_at,1,19)||(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(newer.knowledge_at,-6) WHEN "
                "substr(newer.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS "
                "INTEGER)*1000000+CAST(substr((CASE WHEN substr(newer.knowledge_at,20,1)='.' THEN "
                "substr(newer.knowledge_at,21,length(newer.knowledge_at)-20-(CASE WHEN newer.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(newer.knowledge_at,-1)='Z' THEN 1 ELSE 0 "
                "END)) ELSE '' END)||'000000',1,6) AS INTEGER)) END)<=(CASE WHEN "
                "(substr(NEW.knowledge_at,20)=(CASE WHEN NEW.knowledge_at GLOB '*[+-][0-9][0-9]:[0-9][0-9]' "
                "THEN substr(NEW.knowledge_at,-6) WHEN substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END) "
                "OR (substr(NEW.knowledge_at,20,1)='.' AND length((CASE WHEN substr(NEW.knowledge_at,20,1)='.' "
                "THEN substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)) BETWEEN 1 AND 6 AND (CASE WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END) NOT GLOB '*[^0-9]*')) THEN "
                "(CAST(strftime('%s',substr(NEW.knowledge_at,1,19)||(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN substr(NEW.knowledge_at,-6) WHEN "
                "substr(NEW.knowledge_at,-1)='Z' THEN 'Z' ELSE '' END)) AS INTEGER)*1000000+CAST(substr((CASE "
                "WHEN substr(NEW.knowledge_at,20,1)='.' THEN "
                "substr(NEW.knowledge_at,21,length(NEW.knowledge_at)-20-(CASE WHEN NEW.knowledge_at GLOB "
                "'*[+-][0-9][0-9]:[0-9][0-9]' THEN 6 WHEN substr(NEW.knowledge_at,-1)='Z' THEN 1 ELSE 0 END)) "
                "ELSE '' END)||'000000',1,6) AS INTEGER)) END)))))",
            ),
        ),
    ),
)


def _rewrite(*, upgrade_subjects: bool) -> None:
    bind = op.get_bind()
    rewrites: list[tuple[str, str]] = []
    for name, prior_sha, next_sha, substitutions in _REWRITES:
        sql = bind.execute(
            text("SELECT sql FROM sqlite_master WHERE type='trigger' AND name=:name"),
            {"name": name},
        ).scalar_one_or_none()
        expected_sha = prior_sha if upgrade_subjects else next_sha
        if not isinstance(sql, str) or hashlib.sha256(sql.encode()).hexdigest() != expected_sha:
            raise RuntimeError(f"KPI subject trigger {name} differs from its predecessor")
        rewritten = sql
        for prior, successor in substitutions:
            target, replacement = (prior, successor) if upgrade_subjects else (successor, prior)
            if rewritten.count(target) != 1:
                raise RuntimeError(f"KPI subject trigger {name} has an unknown identity predicate")
            rewritten = rewritten.replace(target, replacement, 1)
        result_sha = next_sha if upgrade_subjects else prior_sha
        if hashlib.sha256(rewritten.encode()).hexdigest() != result_sha:
            raise RuntimeError(f"KPI subject trigger {name} reconstruction differs")
        rewrites.append((name, rewritten))
    if (
        not upgrade_subjects
        and bind.exec_driver_sql(
            "SELECT 1 FROM kpi_definition_revisions definition "
            "JOIN evidence_document_versions document "
            "ON document.document_version_id=definition.source_document_version_id "
            "JOIN reporting_entities entity ON entity.reporting_entity_id=definition.reporting_entity_id "
            "WHERE document.issuer_id<>entity.issuer_id "
            "UNION ALL SELECT 1 FROM kpi_definition_comparability_revisions relation "
            "JOIN kpi_definition_revisions successor "
            "ON successor.kpi_definition_revision_id=relation.successor_definition_revision_id "
            "JOIN reporting_entities entity ON entity.reporting_entity_id=successor.reporting_entity_id "
            "JOIN evidence_document_versions document "
            "ON document.document_version_id=relation.source_document_version_id "
            "WHERE document.issuer_id<>entity.issuer_id "
            "UNION ALL SELECT 1 FROM kpi_fact_semantic_contexts context "
            "JOIN kpi_definition_revisions definition "
            "ON definition.kpi_definition_revision_id=context.kpi_definition_revision_id "
            "JOIN reporting_entities entity ON entity.reporting_entity_id=definition.reporting_entity_id "
            "JOIN kpi_facts fact ON fact.id=context.kpi_fact_id "
            "WHERE entity.issuer_id<>COALESCE(           (SELECT document.issuer_id           FROM v_legacy_document_evidence_bindings_current binding           JOIN evidence_document_versions document            ON document.document_version_id=binding.document_version_id           WHERE binding.legacy_document_id=fact.source_doc_id LIMIT 1),           (SELECT document.issuer_id           FROM evidence_document_versions document           WHERE document.legacy_document_id=fact.source_doc_id           ORDER BY document.version_sequence DESC LIMIT 1)) LIMIT 1"
        ).first()
        is not None
    ):
        raise RuntimeError("cannot remove KPI subject bindings while dependent rows are retained")
    # Validate every predecessor before dropping any guard.
    for name, rewritten in rewrites:
        bind.exec_driver_sql(f"DROP TRIGGER {name}")
        bind.exec_driver_sql(rewritten)


def upgrade() -> None:
    _rewrite(upgrade_subjects=True)


def downgrade() -> None:
    _rewrite(upgrade_subjects=False)
