@echo off
REM Daily 04:00 — fan registered triggers across the user's portfolio + watchlist
REM + evaluation list. Persists fresh alerts + drafted actions into
REM data/portfolio.db.alerts / .queued_actions; the dashboard digest (already
REM regenerated by run_daily_fetch_and_brief.bat at 06:30) picks them up.
REM
REM Runs ahead of the 06:30 brief refresh so morning digests see the night's
REM newly-fired alerts. The per-run cost cap ($10) is a hard ceiling on a
REM single invocation — accumulated llm_calls.cost_estimate_usd since the
REM driver started; reaching it halts cleanly with exit 0.

setlocal
set PROJECT_ROOT=%USERPROFILE%\.gemini\antigravity\scratch\earnings-summary
set LOG_DIR=%PROJECT_ROOT%\.tmp\cron_logs
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

REM wmic was removed from Windows 11 24H2+; use PowerShell for the UTC stamp.
for /f "usebackq tokens=*" %%t in (`powershell -NoProfile -Command "(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')"`) do set "TS=%%t"

set LOG_FILE=%LOG_DIR%\run_triggers_%TS%.log

cd /d "%PROJECT_ROOT%"
python execution\run_triggers.py --max-cost-usd 10 > "%LOG_FILE%" 2>&1

endlocal
