/* Shared illustrative semantic catalog for the isolated Explore mockups.
   Production would populate this shape from the governed metric resolver. */
window.EXPLORE_METRIC_DEFINITIONS = {
  commerce: {label:'Commerce revenue',category:'Income statement',canonical:'Revenue attributable to the Commerce operating ecosystem for the stated fiscal period.',issuer:'MELI’s issuer presentation for commerce-related marketplace, advertising, logistics, and related services. Effective Q4 ’25, MELI reclassified shipping platform fees and ad services (disclosed in Shareholder Letter Q4 ’25, Note 3 Segment Reporting, p. 8). Pre-Q4 ’25 and Post-Q4 ’25 periods are discontinuous.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported',source:'Shareholder letter · segment note (doc:meli-2025-q4-p8)',dcf:'Mapped read-only to Commerce revenue in DCF revision 184',comparability:'Discontinuous series at Q4 ’25. Effective Q4 ’25, MELI reclassified shipping platform and advertising allocations between Commerce and Fintech (Shareholder Letter Q4 ’25, Note 3 Segment Reporting, p. 8, doc:meli-2025-q4-p8). Figures before and after Q4 ’25 are not directly comparable without pro-forma reconciliation. Continuous multi-year CAGR across this boundary is non-continuous and requires adjustment.'},
  fintech: {label:'Fintech revenue',category:'Income statement',canonical:'Revenue attributable to the Fintech operating ecosystem for the stated fiscal period.',issuer:'MELI’s issuer presentation for payments, credit, acquiring, and related financial services. Effective Q4 ’25, MELI updated allocation of merchant fees and gateway revenue (disclosed in Shareholder Letter Q4 ’25, Note 3 Segment Reporting, p. 8). Pre-Q4 ’25 and Post-Q4 ’25 periods are discontinuous.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported',source:'Shareholder letter · segment note (doc:meli-2025-q4-p8)',dcf:'Mapped read-only to Fintech revenue in DCF revision 184',comparability:'Discontinuous series at Q4 ’25. Effective Q4 ’25, MELI updated allocation of merchant fees and gateway revenue (Shareholder Letter Q4 ’25, Note 3 Segment Reporting, p. 8, doc:meli-2025-q4-p8). Figures before and after Q4 ’25 are not directly comparable without pro-forma reconciliation. Continuous multi-year CAGR across this boundary is non-continuous and requires adjustment.'},
  share: {label:'Fintech revenue share',category:'Calculated metric',canonical:'Fintech revenue divided by the sum of Commerce and Fintech revenue for the same admitted period and basis.',issuer:'Explore calculation; not an issuer-reported line item.',unit:'Percent',period:'Quarterly duration',basis:'Calculated from issuer-reported observations',source:'Commerce revenue + Fintech revenue',dcf:'Not directly used in the DCF'},
  tpv: {label:'Total payment volume',category:'Marketplace & payments',canonical:'Total value of payment transactions processed through the payments platform during the stated period.',issuer:'Issuer-reported TPV, subject to the geographic and on-platform/off-platform scope disclosed for the period.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported KPI',source:'Shareholder letter · Fintech KPIs',dcf:'Not used in the current DCF'},
  gmv: {label:'Gross merchandise volume',category:'Marketplace & payments',canonical:'Total value of merchandise transacted through the marketplace during the stated period before returns and cancellations as disclosed.',issuer:'Issuer-reported GMV under the company’s period-specific marketplace scope.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported KPI',source:'Shareholder letter · Commerce KPIs',dcf:'Not used in the current DCF'},
  users: {label:'Fintech active users',category:'Marketplace & payments',canonical:'Distinct users meeting the issuer’s active-use criterion for Fintech products during the measurement window.',issuer:'The active-user threshold and product inclusion follow the effective issuer definition for each period.',unit:'Users, millions',period:'Period-end / trailing activity window',basis:'Issuer reported KPI',source:'Shareholder letter · Fintech KPIs',dcf:'Not used in the current DCF'},
  portfolio: {label:'Credit portfolio',category:'Credit & risk',canonical:'Outstanding principal balance of the issuer’s credit portfolio at the stated period end.',issuer:'Issuer-reported managed credit portfolio, with product and geography scope carried from the source definition.',unit:'USD billions',period:'Period end',basis:'Issuer reported KPI',source:'Shareholder letter · Credit note',dcf:'Not used in the current DCF'},
  originations: {label:'Credit originations',category:'Credit & risk',canonical:'Principal value of credit originated during the stated fiscal period.',issuer:'Issuer-reported consumer and merchant credit originations under the effective product scope.',unit:'USD billions',period:'Quarterly duration',basis:'Issuer reported KPI',source:'Shareholder letter · Credit note',dcf:'Not used in the current DCF'},
  npl: {label:'15–90 day NPL ratio',category:'Credit & risk',canonical:'Balance of loans 15 to 90 days past due divided by the applicable credit portfolio balance.',issuer:'Issuer-reported early-stage delinquency ratio under the period-specific portfolio scope.',unit:'Percent',period:'Period end',basis:'Issuer reported KPI',source:'Shareholder letter · Asset quality table',dcf:'Not used in the current DCF'},
  ocf: {label:'Operating cash flow',category:'Cash flow statement',canonical:'Net cash provided by operating activities for the stated fiscal period.',issuer:'Consolidated cash flow statement value under the issuer’s reporting currency and accounting basis.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported · IFRS',source:'Cash flow statement',dcf:'Not used as a direct DCF line item'},
  capex: {label:'Capital expenditures',category:'Cash flow statement',canonical:'Cash additions to property, equipment, and qualifying intangible assets during the stated period.',issuer:'Explore calculation from disclosed investing cash-flow components using the effective capex policy.',unit:'USD millions',period:'Quarterly duration',basis:'Calculated from issuer-reported facts',source:'Cash flow statement · investing activities',dcf:'Referenced by the DCF only through its separately owned capex forecast'},
  cash: {label:'Cash and equivalents',category:'Balance sheet',canonical:'Cash and cash equivalents recognized at the stated reporting date.',issuer:'Consolidated balance-sheet cash and equivalents under the issuer’s accounting basis.',unit:'USD millions',period:'Period end',basis:'Issuer reported · IFRS',source:'Balance sheet',dcf:'Used in net-debt reconciliation, view-only here'},
  inventory: {label:'Inventory',category:'Balance sheet',canonical:'Carrying value of inventories recognized at the stated reporting date.',issuer:'Consolidated inventory balance under the issuer’s accounting basis.',unit:'USD millions',period:'Period end',basis:'Issuer reported · IFRS',source:'Balance sheet',dcf:'Not used in the current DCF'},
  leases: {label:'Lease liabilities',category:'Balance sheet',canonical:'Current and non-current lease obligations recognized at the stated reporting date.',issuer:'Consolidated lease liability under the issuer’s accounting basis.',unit:'USD millions',period:'Period end',basis:'Issuer reported · IFRS',source:'Balance sheet · lease note',dcf:'Used only in the valuation bridge, view-only here'},
  headcount: {label:'Employee headcount',category:'Workforce & operations',canonical:'Employees included in the issuer’s disclosed workforce count at the stated date.',issuer:'Scope follows the issuer’s period-specific employee-count disclosure.',unit:'Employees',period:'Period end',basis:'Management-reported indicator',source:'Earnings materials · workforce disclosure',dcf:'Not used in the current DCF'},
  ads: {label:'Advertising revenue',category:'Management indicators',canonical:'Revenue attributed to advertising products under the issuer’s effective disclosure scope.',issuer:'Management-reported advertising revenue or growth observation; promotion to a recurring series depends on disclosure continuity.',unit:'USD millions',period:'Quarterly duration',basis:'Management-reported indicator',source:'Earnings materials · management KPI',dcf:'Not used in the current DCF'},
  shipping: {label:'Shipping cost',category:'Workforce & operations',canonical:'Fulfillment and shipping expense admitted under the effective operating-cost definition.',issuer:'Issuer disclosure may combine or reclassify logistics components; definition revisions remain explicit.',unit:'USD millions',period:'Quarterly duration',basis:'Issuer reported or calculated',source:'Expense note · logistics disclosure',dcf:'Not used in the current DCF'}
};

window.EXPLORE_METRIC_CATALOG = [
  {id:'commerce',preset:'segments',category:'Income statement',aliases:'segment commerce marketplace revenue'},
  {id:'fintech',preset:'segments',category:'Income statement',aliases:'segment fintech payments revenue'},
  {id:'share',preset:'segments',category:'Calculated metric',aliases:'mix contribution segment share'},
  {id:'tpv',preset:'payments',category:'Marketplace & payments',aliases:'payment volume payments'},
  {id:'gmv',preset:'payments',category:'Marketplace & payments',aliases:'merchandise marketplace volume'},
  {id:'users',preset:'payments',category:'Marketplace & payments',aliases:'active users mau fintech'},
  {id:'portfolio',preset:'credit',category:'Credit & risk',aliases:'loan book receivables credit'},
  {id:'originations',preset:'credit',category:'Credit & risk',aliases:'new loans credit volume'},
  {id:'npl',preset:'credit',category:'Credit & risk',aliases:'delinquency nonperforming loans asset quality'},
  {id:'ocf',preset:'custom',category:'Cash flow statement',aliases:'cash from operations CFO',display:'currency',values:[1280,1410,1190,1520,1640,1780,1690,1960],compare:'15.3%'},
  {id:'capex',preset:'custom',category:'Cash flow statement',aliases:'capital expenditures investing cash flow',display:'currency',values:[420,455,470,510,545,590,610,660],compare:'16.3%'},
  {id:'cash',preset:'custom',category:'Balance sheet',aliases:'cash equivalents liquidity',display:'currency',values:[6210,6480,6350,6720,7010,7460,7590,8120],compare:'14.3%'},
  {id:'inventory',preset:'custom',category:'Balance sheet',aliases:'inventories stock working capital',display:'currency',values:[1120,1190,1260,1330,1410,1490,1550,1630],compare:'13.6%'},
  {id:'leases',preset:'custom',category:'Balance sheet',aliases:'lease debt liabilities obligations',display:'currency',values:[1820,1870,1910,1980,2050,2110,2180,2240],compare:'7.2%'},
  {id:'headcount',preset:'custom',category:'Workforce & operations',aliases:'employees workforce people',display:'number',values:[58200,59600,60700,62100,63800,65100,66700,68400],compare:'8.5%'},
  {id:'ads',preset:'custom',category:'Management indicators',aliases:'advertising ads retail media',display:'currency',values:[310,342,375,418,466,512,568,631],compare:'42.7%'},
  {id:'shipping',preset:'custom',category:'Workforce & operations',aliases:'logistics fulfillment delivery expense',display:'currency',values:[890,925,970,1010,1060,1115,1170,1235],compare:'11.6%'}
];
